### PR TITLE
Improve workshop UI

### LINKED ISSUE #74: Improve Workshop UI
- Introduce navbar
- Don't show qualification task upload form when workshop is not qualifying
- Better formatting

### PR DESCRIPTION
**Pull request by krzys-h**
* Proposal and public page editors were merged, to clear up confusion
  where some of the details visible on the public page were taken
  from the proposal (title, category etc.)
* All input fields are now grouped logically
* Users with see_all_workshops permission, but without the edit_all_workshops
  permission can now see all fields as read-only. Previously, they could
  only see the workshop proposal.
* The qualification tasks and results input fields are disabled if the workshop is not
  qualifying
* The form layout is improved in general
* Not qualifying workshops are now displayed correctly in the qualification results
  on the program page (they were displayed like all others where there are no results
  yet, now they are displayed as "-")
* Made sure that if the workshop is toggled to not qualifying after some results were already
 entered, the results don't count. They are still kept in the database in case its toggled back.

To be merged after #238, so I'm marking it as a draft for now

Closes #74

screencapture-localhost-8000-workshop-przetestujmy-cos-edit-2020-08-21-13_38_10
screencapture-localhost-8000-workshop-przetestujmy-cos-edit-2020-08-21-13_43_27
image

---
This change is [Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/240)

### CODE REVIEW

**Review by cytadela8 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r4, 4 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/240)* status: 5 of 12 files reviewed, 1 unresolved discussion (waiting on @cytadela8 and @krzys-h)

___
*[wwwapp/forms.py, line 170 at r5](https://reviewable.io/reviews/warsztatywww/aplikacjawww/240#-MFVdD234oNzdVrYbqpR:-MFVdD234oNzdVrYbqpS:b-625osh) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/5beead1bc9793edbc296a4eb67f9c955ed7c9ae0/wwwapp/forms.py#L170)):*
> ```Python
> 
> class WorkshopForm(ModelForm):
>     category = ModelMultipleChoiceField(label="Kategorie", queryset=WorkshopCategory.objects.filter(year=settings.CURRENT_YEAR),
> ```

`settings.CURRENT_YEAR` was removed (by you :P)

Here and below

**Review by krzys-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/240)* status: 5 of 12 files reviewed, 1 unresolved discussion (waiting on @cytadela8 and @krzys-h)

___
*[wwwapp/forms.py, line 170 at r5](https://reviewable.io/reviews/warsztatywww/aplikacjawww/240#-MFVdD234oNzdVrYbqpR:-MFVfG-w-0xPY-S3s1nO:b2jvykk) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/5beead1bc9793edbc296a4eb67f9c955ed7c9ae0/wwwapp/forms.py#L170)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

`settings.CURRENT_YEAR` was removed (by you :P)

Here and below
</blockquote></details>

Rebasing is hard...

(and it worked because it's not removed from settings yet because the migration uses it to set the start and end date, we'll remove it after the migration is done)

**Review by krzys-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/240)* status: 5 of 12 files reviewed, 1 unresolved discussion (waiting on @cytadela8 and @krzys-h)

___
*[wwwapp/forms.py, line 170 at r5](https://reviewable.io/reviews/warsztatywww/aplikacjawww/240#-MFVdD234oNzdVrYbqpR:-MFVhJwf4ITLe23y_Le5:b-896fix) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/5beead1bc9793edbc296a4eb67f9c955ed7c9ae0/wwwapp/forms.py#L170)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

Rebasing is hard...

(and it worked because it's not removed from settings yet because the migration uses it to set the start and end date, we'll remove it after the migration is done)
</blockquote></details>

Done.

**Review by cytadela8 — CHANGES_REQUESTED** [review]
Please grant AGPL v3 Licence by rebasing on top of code with LICENCE.

> Reviewed 2 of 2 files at r6, 7 of 7 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/240#-:-MHEeKPS8W_A_aC58qFl:b-nooiao)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[templates/workshopbase.html, line 12 at r7](https://reviewable.io/reviews/warsztatywww/aplikacjawww/240#-MHEdOaK4c-Z20laPVeI:-MHEdOaK4c-Z20laPVeJ:b-qva8nd) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/114b37b6198a7c14a84eb65b47c7e8953f6ab324/templates/workshopbase.html#L12)):*
> ```HTML
>           <div>
>             <a href="{% url 'workshop_page' workshop.name %}">Strona warsztatów</a> |
>             <a href="{% url 'workshop_edit' workshop.name %}">Edycja warsztatów</a> |
> ```

BTW, We could use a better menu in the feature. (probably it will never get done)
___
*[wwwapp/forms.py, line 171 at r6](https://reviewable.io/reviews/warsztatywww/aplikacjawww/240#-MHEcELOD08R1jdllWGi:-MHEcELOD08R1jdllWGj:b-l46uut) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/1e8336662d53cae4eab8ca15208ed52ebc5b0e1d/wwwapp/forms.py#L171)):*
> ```Python
> class WorkshopForm(ModelForm):
>     # Note that the querysets for category and type are overwritten in __init__, but the argument is required here
>     category = ModelMultipleChoiceField(label="Kategorie", queryset=WorkshopCategory.objects.all(),
> ```

Fun fact, the fancy category edditing widget doesn't load sometimes for me. I think it needs to load something from internet somewhere??? (I'm on a terrible conn)

**Review by krzys-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/240)* status: 5 of 12 files reviewed, all discussions resolved (waiting on @cytadela8)

___
*[templates/workshopbase.html, line 12 at r7](https://reviewable.io/reviews/warsztatywww/aplikacjawww/240#-MHEdOaK4c-Z20laPVeI:-MI3VRE28ckWEPszTu6J:btx91at) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/114b37b6198a7c14a84eb65b47c7e8953f6ab324/templates/workshopbase.html#L12)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

BTW, We could use a better menu in the feature. (probably it will never get done)
</blockquote></details>

Maybe when (and if) we do the redesign in the future. For now at least the tabs are not confusing.
___
*[wwwapp/forms.py, line 171 at r6](https://reviewable.io/reviews/warsztatywww/aplikacjawww/240#-MHEcELOD08R1jdllWGi:-MI3VXmU5QAwBdaf9XbC:b-g5fvyr) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/1e8336662d53cae4eab8ca15208ed52ebc5b0e1d/wwwapp/forms.py#L171)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

Fun fact, the fancy category edditing widget doesn't load sometimes for me. I think it needs to load something from internet somewhere??? (I'm on a terrible conn)
</blockquote></details>

Yeah, it looks like you are right

#247

**Review by cytadela8 — APPROVED** [review]
> Reviewed 7 of 7 files at r9, 7 of 7 files at r10, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/240)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
