### PR TITLE
Fix TinyMCE removing <iframe> on index page

### LINKED ISSUE #281: The Facebook embed has disappeared
I edited the main page yesterday from "warsztaty odbędą się ..."  to "warsztaty odbyły się ..." and I just noticed that the Facebook embed disappeared because of that. When I try to add it back, tinymce cuts it out again before I even get to click save. I'm sure this used to work before, did TinyMCE update or something? Note that `<iframe>` does not seem to be in the list of allowed tags passed to TinyMCE, it's only added to bleach config when displaying the page (we still do the cleaning during display not saving...)

Here is the original embed code from my local copy for reference:
```
<div class="col-md-4 hidden-sm hidden-xs" style="text-align: center;"><iframe height="500" src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Fwarsztatywww%2F&amp;tabs=timeline&amp;width=340&amp;height=500&amp;small_header=false&amp;adapt_container_width=false&amp;hide_cover=false&amp;show_facepile=true&amp;appId=1522345984699744" style="border: none; width: 100%; min-width: 180px; max-width: 500px;"></iframe></div>
<div class="col-xs-12 hidden-md hidden-lg hidden-xl" style="text-align: center;"><iframe height="214" src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Fwarsztatywww%2F&amp;tabs&amp;width=500&amp;height=214&amp;small_header=false&amp;adapt_container_width=false&amp;hide_cover=false&amp;show_facepile=true&amp;appId=1522345984699744" style="border: none; width: 100%; min-width: 180px; max-width: 500px;"></iframe></div>
```

### PR DESCRIPTION
**Pull request by krzys-h**
Not sure how it ever worked before...

Closes #281

---
This change is [Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/284)

### CODE REVIEW

**Review by cytadela8 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/284)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @cytadela8 and @krzys-h)

___
*[wwwapp/forms.py, line 181 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/284#-MQSeIMN9atVgLg56UQJ:-MQSeIMN9atVgLg56UQK:b-obfhs2) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/eef65b12a77fce5a6bb872f68355aea41fcd5896/wwwapp/forms.py#L181)):*
> ```Python
>         if self.instance and self.instance.name == 'index':
>             # Allow iframe on main page for Facebook embed
>             mce_attrs['valid_elements'] = '@[%s],%s' % ('|'.join(settings.BLEACH_ALLOWED_ATTRIBUTES), ','.join(settings.BLEACH_ALLOWED_TAGS + ['iframe']))
> ```

Stupid question. Why not just `+=',iframe'`?

**Review by krzys-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/284)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @krzys-h)

___
*[wwwapp/forms.py, line 181 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/284#-MQSeIMN9atVgLg56UQJ:-MQSenBXB9tv_UO7SQgL:bmskkt0) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/eef65b12a77fce5a6bb872f68355aea41fcd5896/wwwapp/forms.py#L181)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

Stupid question. Why not just `+=',iframe'`?
</blockquote></details>

Because I was being stupid and tried to add it to BLEACH_ALLOWED_ATTRIBUTES instead of BLEACH_ALLOWED_TAGS earlier... good point, will change in a moment

**Review by krzys-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/284)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @cytadela8)

___
*[wwwapp/forms.py, line 181 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/284#-MQSeIMN9atVgLg56UQJ:-MQT0Syw4539CNYyHKct:b-896fix) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/eef65b12a77fce5a6bb872f68355aea41fcd5896/wwwapp/forms.py#L181)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

Because I was being stupid and tried to add it to BLEACH_ALLOWED_ATTRIBUTES instead of BLEACH_ALLOWED_TAGS earlier... good point, will change in a moment
</blockquote></details>

Done.

**Review by cytadela8 — APPROVED** [review]
:duck: 

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/284#-:-MQTCRaC1jntkx5feQiT:bcmjph0)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
