### PR TITLE
Display checked solution count in workshop and participant list views

### LINKED ISSUE #483: Add checked solutions count and "all solution checked" checkmark to the workshop list
Would be useful to know who to ping to finish checking their qualification tasks

(originally requested by @cytadela8 a few days ago)

### PR DESCRIPTION
**Pull request by krzys-h**
Closes #483

---
This change is [Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/484)

### CODE REVIEW

**Review by cytadela8 — APPROVED** [review]
:duck: 

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/484#-:-Mb7eNqADtQxXuTLAXVD:bcmjph0)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by cytadela8 — APPROVED** [review]
Rebase please

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/484#-:-Mb7eerIDmegYrnV7enZ:b-ujmq67)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by krzys-h — COMMENTED** [review]
> Rebase please

Done

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/484#-:-Mb87ETF7qorQFzI13XV:b13022p)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @cytadela8)

**Review by cytadela8 — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/484)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
