### PR TITLE
Don't say "your workshop" when this is in fact an admin looking at somebody else's workshop

### PR DESCRIPTION
**Pull request by krzys-h**
This change is [Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/298)

### CODE REVIEW

**Review by cytadela8 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/298)* status: all files reviewed, 4 unresolved discussions (waiting on @krzys-h)

___
*[templates/workshoppage.html, line 22 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/298#-MQm2L2e1hJ-UuhOJhw5:-MQm2L2e1hJ-UuhOJhw6:b-ph5s7o) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/d763280df3ead5af997c8d56c6d0f59b1aa7aefd/templates/workshoppage.html#L22)):*
> ```HTML
>         <p>Nie ma jeszcze zadań kwalifikacyjnych.</p>
>       {% elif has_perm_to_edit %}
>         <div class="alert alert-danger" role="alert">Nie ma jeszcze zadań kwalifikacyjnych.</div>
> ```

Minor, I think `alert-info` would be better
___
*[templates/workshoppage.html, line 32 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/298#-MQm2SCT-oHdLApt8yAQ:-MQm2SCT-oHdLApt8yAR:b-ph5s7o) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/d763280df3ead5af997c8d56c6d0f59b1aa7aefd/templates/workshoppage.html#L32)):*
> ```HTML
>     </div>
>   {% elif is_lecturer %}
>     <div class="alert alert-danger" role="alert">Nie opublikowałeś jeszcze opisu!</div>
> ```

Minor, I think `alert-info` would be better
___
*[wwwapp/views.py, line 460 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/298#-MQmAWXmAdl52eJXHmZ5:-MQmAWXmAdl52eJXHmZ6:b-n5k3vw) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/d763280df3ead5af997c8d56c6d0f59b1aa7aefd/wwwapp/views.py#L460)):*
> ```Python
>     workshop_participant = WorkshopParticipant.objects.get(id=request.POST['id'])
> 
>     has_perm_to_edit, is_lecturer = can_edit_workshop(workshop_participant.workshop, request.user)
> ```

Prefix with `_` to signify intentionally unused variable
___
*[wwwapp/views.py, line 937 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/298#-MQmAeum11e79p793hiM:-MQmAeum11e79p793hiN:b-n5k3vw) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/d763280df3ead5af997c8d56c6d0f59b1aa7aefd/wwwapp/views.py#L937)):*
> ```Python
> def workshop_edit_upload_file(request, year, name):
>     workshop = get_object_or_404(Workshop, year__pk=year, name=name)
>     has_perm_to_edit, is_lecturer = can_edit_workshop(workshop, request.user)
> ```

Prefix with `_` to signify intentionally unused variable

**Review by krzys-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/298)* status: all files reviewed, 4 unresolved discussions (waiting on @cytadela8 and @krzys-h)

___
*[templates/workshoppage.html, line 22 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/298#-MQm2L2e1hJ-UuhOJhw5:-MQmBlHV2SYfgsQYD6vz:bkob68c) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/d763280df3ead5af997c8d56c6d0f59b1aa7aefd/templates/workshoppage.html#L22)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

Minor, I think `alert-info` would be better
</blockquote></details>

You want `info` for:

* Missing tasks in public view
* Missing page in lecturer view

but keep `danger` for:

* Missing tasks in lecturer view
* Missing page in public view

How does that make any sense?!

Either keep all as danger, change all to info or use info for public view and danger for lecturer view

**Review by cytadela8 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/298)* status: all files reviewed, 4 unresolved discussions (waiting on @krzys-h)

___
*[templates/workshoppage.html, line 22 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/298#-MQm2L2e1hJ-UuhOJhw5:-MQmPe6qEN2g-2J9WFyM:b-60vw9n) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/d763280df3ead5af997c8d56c6d0f59b1aa7aefd/templates/workshoppage.html#L22)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

You want `info` for:

* Missing tasks in public view
* Missing page in lecturer view

but keep `danger` for:

* Missing tasks in lecturer view
* Missing page in public view

How does that make any sense?!

Either keep all as danger, change all to info or use info for public view and danger for lecturer view
</blockquote></details>

info for public view, danger for lecturer view.
___
*[wwwapp/views.py, line 460 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/298#-MQmAWXmAdl52eJXHmZ5:-MQmQ09q9A09E007hgfh:b-1quhyu) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/d763280df3ead5af997c8d56c6d0f59b1aa7aefd/wwwapp/views.py#L460)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

Prefix with `_` to signify intentionally unused variable
</blockquote></details>

Also I thought you are strongly against unnecessary DB requests :zany_face:

**Review by krzys-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/298)* status: all files reviewed, 3 unresolved discussions (waiting on @cytadela8 and @krzys-h)

___
*[templates/workshoppage.html, line 22 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/298#-MQm2L2e1hJ-UuhOJhw5:-MQmRvC7DK3b_KNYVtHq:b-vh7jss) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/d763280df3ead5af997c8d56c6d0f59b1aa7aefd/templates/workshoppage.html#L22)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

info for public view, danger for lecturer view.
</blockquote></details>

Ok, will do
___
*[wwwapp/views.py, line 460 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/298#-MQmAWXmAdl52eJXHmZ5:-MQmRz6q-LXNgAOmQ9NM:b-c3n81h) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/d763280df3ead5af997c8d56c6d0f59b1aa7aefd/wwwapp/views.py#L460)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

Also I thought you are strongly against unnecessary DB requests :zany_face:
</blockquote></details>

I am, which is why this is written the way it is (returning two variables). `has_perm_to_edit = is_lecturer or edit_all_workshops`, but I sometimes need the intermediate is_lecturer as well. Using only is_lecturer might be an unnecessary query (depending on how Django caches permissions), using only has_perm_to_edit is not.

**Review by cytadela8 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/298)* status: all files reviewed, 3 unresolved discussions (waiting on @krzys-h)

___
*[wwwapp/views.py, line 460 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/298#-MQmAWXmAdl52eJXHmZ5:-MQmTIGi5OQJ116ZdsR8:bpvc0g5) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/d763280df3ead5af997c8d56c6d0f59b1aa7aefd/wwwapp/views.py#L460)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

I am, which is why this is written the way it is (returning two variables). `has_perm_to_edit = is_lecturer or edit_all_workshops`, but I sometimes need the intermediate is_lecturer as well. Using only is_lecturer might be an unnecessary query (depending on how Django caches permissions), using only has_perm_to_edit is not.
</blockquote></details>

Oh, it's intermediate. Right. Then just add `_`

**Review by krzys-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/298)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @cytadela8)

___
*[wwwapp/views.py, line 460 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/298#-MQmAWXmAdl52eJXHmZ5:-MR0QxEX58B2svmr2W02:b-896fix) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/d763280df3ead5af997c8d56c6d0f59b1aa7aefd/wwwapp/views.py#L460)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

Oh, it's intermediate. Right. Then just add `_`
</blockquote></details>

Done.
___
*[wwwapp/views.py, line 937 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/298#-MQmAeum11e79p793hiM:-MR0QxqpEbPiY0Vyk2rI:b-896fix) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/d763280df3ead5af997c8d56c6d0f59b1aa7aefd/wwwapp/views.py#L937)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

Prefix with `_` to signify intentionally unused variable
</blockquote></details>

Done.

**Review by cytadela8 — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/298)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
