### PR TITLE
Improve late proposal management

### LINKED ISSUE #442: The "program is not final" message should disappear later
Currently, the message disappears as soon as registration closes, not leaving us any time for approvals. I'm not sure what the actual date should be - maybe the date when workshop pages should be finished?

### LINKED ISSUE #444: Change proposal block into a warning
I don't like the proposal block (although I admin I have had approved it). I think a warning on the new workshop form (and :warning: icon on workshop admin list) would be much better.

### PR DESCRIPTION
**Pull request by krzys-h**
* Delay disapperance of the "program not final" message until a bit after proposal_end_date, so that we have a chance to accept the workshops. A new flag `program_finalized` was added to the Camp object for this purpose. Closes #442.
* Allow late proposals. The proposal form will now stay open even after proposal_end_date, until program_finalized is set. A warning appears in the editor when trying to submit a late proposal. Closes #444.

---
This change is [Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/574)

### CODE REVIEW

**Review by cytadela8 — DISMISSED** [review]
> Reviewed 7 of 7 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/574)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by krzys-h** [comment]
Not merging this yet, because the migrations will cause a merge conflict with #571 and fixing this PR is going to be much easier if needed because it's smaller.

**Comment by krzys-h** [comment]
Rebased to fix migration order, plz re-approve

**Review by cytadela8 — APPROVED** [review]
:duck: 

> Reviewed 7 of 7 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/574#-:-MyptrZF1MsbA-NZaRf5:bcmjph0)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
