### PR TITLE
Improved login buttons

### LINKED ISSUE #214: Resize social buttons
Currently social buttons have different sizes. They should be the same size and have similar style.

### PR DESCRIPTION
**Pull request by krzys-h**
I did my best to make sure they don't break the [Google](https://developers.google.com/identity/branding-guidelines) and [Facebook](https://developers.facebook.com/docs/facebook-login/userexperience/#buttondesign) style guidelines but let me know if you see anything that is wrong

Closes #214

---
This change is [Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/229)

### CODE REVIEW

**Review by krzys-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/229)* status: 0 of 16 files reviewed, 1 unresolved discussion

___
*[templates/loginMerge.html, line 16 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/229#-MF6URSh2_xBPA_bdfru:-MF6URSh2_xBPA_bdfrv:b-4yt0i5) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/f1ac4fefaf6e6e95ca68ec9c2e9d0f2969926021/templates/loginMerge.html#L16)):*
> ```HTML
>           <div class="row">
>             <div class="col-md-6">
>               {% include "_socialButton.html" with provider=provider next="/accounts/verified/" only %}
> ```

I know this is not perfect, but I wasted enough time trying to get `{% url %}` to work inside the `{% include %}` parameter, let me know if you see any way to do this

**Comment by krzys-h** [comment]
screencapture-localhost-8000-login-2020-08-19-18_16_04

**Comment by krzys-h** [comment]
screencapture-localhost-8000-accounts-complete-google-oauth2-2020-08-19-18_17_24

**Review by cytadela8 — CHANGES_REQUESTED** [review]
Could we make the buttons a little bit thicker (higher height)?

Also the button spacing is bad on mobile.


> Reviewed 16 of 16 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/229#-:-MFAakEI6qysDHFzUjAR:bss5qmn)* status: all files reviewed, 1 unresolved discussion

**Review by cytadela8 — CHANGES_REQUESTED** [review]
My issue with button size is mainly with logo size

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/229#-:-MFAbT6W7PSKFVKohv5m:b-w2ng0b)* status: all files reviewed, 1 unresolved discussion

**Comment by krzys-h** [comment]
Well... i guess no? I made them exactly match the Google specs. The specs are not 100% clear on whether this is a recommendation or a requirement, but I'm too afraid to touch it. See https://developers.google.com/identity/branding-guidelines#matching

> The padding to the left (and right) of the text should be 8dp. The logo should be 18dp, and there should be 24dp between the logo and the button text.
>

**Review by cytadela8 — CHANGES_REQUESTED** [review]
Ok, I guess it can stay. I though the logo was bigger previously. Just add some spacing between buttons on mobile.

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/229#-:-MFBP2_37v1eXhkYtwAN:b-k16r2o)* status: all files reviewed, 1 unresolved discussion

**Review by cytadela8 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/229)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[templates/loginMerge.html, line 16 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/229#-MF6URSh2_xBPA_bdfru:-MFBPU_FB_k_M2WcqOBJ:b-bz0gq5) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/f1ac4fefaf6e6e95ca68ec9c2e9d0f2969926021/templates/loginMerge.html#L16)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

I know this is not perfect, but I wasted enough time trying to get `{% url %}` to work inside the `{% include %}` parameter, let me know if you see any way to do this
</blockquote></details>

Hmm, I don't see any easy solution to this.

**Review by krzys-h — COMMENTED** [review]
> Just add some spacing between buttons on mobile.

Done

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/229#-:-MFCBAAY3ATFedV9kfac:b40dhhd)* status: 13 of 17 files reviewed, all discussions resolved (waiting on @cytadela8)

**Review by cytadela8 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/229#-:-MFCicX91kwEcLHo9xpE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
