### PR TITLE
Phone export and minor DataTable improvements

### LINKED ISSUE #491: Save DataTable settings on refresh
- By settings I mean the user changeable elements like list of displayed columns, sorting, etc.
- perhaps put it in the URL after `#` or something?

### LINKED ISSUE #519: Export all phone numbers in an importable format
Phone numbers can be imported to phone book from certain formats. (vcf/vcard is one of them) I believe Google also supported importing a certain csv files. 

Such a feature would be extremly usefull when one wants to call a certain participant during warkshops

### PR DESCRIPTION
**Pull request by krzys-h**
* DataTable state is now stored in the URL. Closes #491
* Make it possible to easily filter DataTables by status. This makes it possible to e.g. export data of only accepted participants
* Add phone number support to wwwforms
* Add phone number export support to DataTables. Closes #519. I only tested importing on https://contacts.google.com/, but it should work everywhere because the vCard format is pretty standard.

---
This change is [Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/573)

### CODE REVIEW

**Review by cytadela8 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 10 of 10 files at r2, 5 of 5 files at r3, 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/573)* status: all files reviewed, 1 unresolved discussion (waiting on @krzys-h)

___
*[frontend/js/datatables_config.js, line 97 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/573#-MydLQXD2ZrT-FTKVbdA:-MydLQXD2ZrT-FTKVbdB:bkv58oq) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/92317e1fd7bf7ff506695adbeb9733d052b2405f/frontend/js/datatables_config.js#L97)):*
> ```JavaScript
>     "stateLoadCallback": function(settings) {
>       const data = atob(window.location.hash.substring(1));
>       return data ? JSON.parse(data) : null;
> ```

Hmm, this looks potentially dangerous. Do you know this is safe for some reason?

I think this may be potentially unsafe thru __proto__: https://github.com/fastify/secure-json-parse

**Review by krzys-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/573)* status: all files reviewed, 1 unresolved discussion (waiting on @krzys-h)

___
*[frontend/js/datatables_config.js, line 97 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/573#-MydLQXD2ZrT-FTKVbdA:-MykoZ6_75ajrTatsxcg:bl4z3kc) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/92317e1fd7bf7ff506695adbeb9733d052b2405f/frontend/js/datatables_config.js#L97)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

Hmm, this looks potentially dangerous. Do you know this is safe for some reason?

I think this may be potentially unsafe thru __proto__: https://github.com/fastify/secure-json-parse
</blockquote></details>

I literally copied the example from the docs (https://datatables.net/reference/option/stateSave), but I think you may have a point, since the URL is a less trusted source than localStorage.

**Review by krzys-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/573)* status: all files reviewed, 1 unresolved discussion (waiting on @cytadela8)

___
*[frontend/js/datatables_config.js, line 97 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/573#-MydLQXD2ZrT-FTKVbdA:-Myl5cIX2GDmVs9mGcU3:b6u010m) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/92317e1fd7bf7ff506695adbeb9733d052b2405f/frontend/js/datatables_config.js#L97)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

I literally copied the example from the docs (https://datatables.net/reference/option/stateSave), but I think you may have a point, since the URL is a less trusted source than localStorage.
</blockquote></details>

As far as I understand, `JSON.parse` by itself is not dangerous. The only point where it becomes dangerous is if you perform a deep copy of such object without validation. At that point I would consider this a vulnerability in DataTables, so I'm tempted to brush it off as "not my problem". I don't expect admins to click direct links to admin pages from untrusted people anyway :P

What do you think?

**Review by cytadela8 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/573)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[frontend/js/datatables_config.js, line 97 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/573#-MydLQXD2ZrT-FTKVbdA:-MypqHrq5kb8waU4c-vp:b-wsw5vu) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/92317e1fd7bf7ff506695adbeb9733d052b2405f/frontend/js/datatables_config.js#L97)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

As far as I understand, `JSON.parse` by itself is not dangerous. The only point where it becomes dangerous is if you perform a deep copy of such object without validation. At that point I would consider this a vulnerability in DataTables, so I'm tempted to brush it off as "not my problem". I don't expect admins to click direct links to admin pages from untrusted people anyway :P

What do you think?
</blockquote></details>

Ok, let's leave this for now, but this is not the only way admins can get to such an url.

**Pull request merged**
