### PR TITLE
Node upgrade

### PR DESCRIPTION
**Pull request by cytadela8**
This change is [Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/618)

### CODE REVIEW

**Review by krzys-h — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/618)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by krzys-h** [comment]
@cytadela8 I think you have to rebase this because you force-pushed things on the other branch

**Review by cytadela8 — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/618#-:-NB39Cwz-hJp7cDEiMQD:bb6un1j)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by krzys-h — APPROVED** [review]
:duck: 

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/618#-:-NB3SWvy8hiH7fwHeKRn:bcmjph0)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
