### PR TITLE
Optimize some SQL queries

### PR DESCRIPTION
**Pull request by krzys-h**
Loading of the people list pages is kinda slow, mostly because data for `UserProfile.all_participation_data()` was not prefetched

On my test database (~ 50 people with debug enabled), in the all people view this gives:

SQL queries: 133 -> 27
Total query time: 2770ms -> 823ms

On production, the difference should be even more noticeable (right now, loading the all people page takes almost 4 seconds)

(this will obviously conflict with #230, but oh well)

---
This change is [Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/245)

### CODE REVIEW

**Review by cytadela8 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/245)* status: all files reviewed, 1 unresolved discussion (waiting on @krzys-h)

___
*[wwwapp/models.py, line 44 at r2](https://reviewable.io/reviews/warsztatywww/aplikacjawww/245#-MFV0ghE6_Cr6QAiuLjm:-MFV0ghE6_Cr6QAiuLjn:bffcjjf) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/43bc6f7d7e7ea05ca19d3d5a26182d43c91609ad/wwwapp/models.py#L44)):*
> ```Python
>         """
>         participant_data = [p for p in self.workshop_profile.all() if p.status is not None]
>         lecturer_data = [p for p in self.lecturer_workshops.all() if p.status is not None]
> ```

Why do you change from filtering in SQl to filtering in Python?

**Review by krzys-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/245)* status: all files reviewed, 1 unresolved discussion (waiting on @cytadela8)

___
*[wwwapp/models.py, line 44 at r2](https://reviewable.io/reviews/warsztatywww/aplikacjawww/245#-MFV0ghE6_Cr6QAiuLjm:-MFV4Y4c8ULfB4YeC9iN:bjypgo1) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/43bc6f7d7e7ea05ca19d3d5a26182d43c91609ad/wwwapp/models.py#L44)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

Why do you change from filtering in SQl to filtering in Python?
</blockquote></details>

Using `.filter()` causes Django to execute a new query rather than using the prefetched data. You could filter it at prefetching time like I did with `workshopparticipant_set`, but this seemed better from code readability perspective and doesn't really have a performance impact (the database did all the heavy work of selecting the objects for the given person already, we can deal with like 5 objects in Python)

Note that I'm doing a similar thing with workshop_profile in participants_view, but there the reasoning is slightly different - I need all workshop_profile objects anyway for all_participation_data(), so I'm doing the filtering in Python to avoid another unnecessary query (and again, at that point there are at most as many of these objects as we had editions registered in the system which is not a lot in the SQL scale of things)

**Review by krzys-h — COMMENTED** [review]
Rebased after camp model merge, and while doing so I managed to somehow accidentaly make it even better (16 queries on the same page I was testing earlier when I got 27).

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/245#-:-MFVTUE9CaGYGlor0Bzj:b-p6qapu)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @cytadela8)

**Review by krzys-h — COMMENTED** [review]
(and after #243 it's probably going to go even lower because we'll cut out having to go through WorkshopType to get the year)

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/245#-:-MFVUkAS8RXO-Oi4reSf:bv4sfuz)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @cytadela8)

**Review by cytadela8 — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/245#-:-MFVZ9HkEFgB82Yh_uQ6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by krzys-h — COMMENTED** [review]
Down to 15! :D

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/245#-:-MFVaONF8oy10e8B7mc5:buqfhbt)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @cytadela8)

**Review by cytadela8 — APPROVED** [review]
> Reviewed 2 of 2 files at r8, 2 of 2 files at r9, 1 of 1 files at r10, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/245)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
