### PR TITLE
Migrate to webpack

### LINKED ISSUE #24: Move to webpack
We should remove all of the autogenerated code from the repo. Why the hell it is there? It should be treated same as binary files

### PR DESCRIPTION
**Pull request by krzys-h**
This PR removes all of the JS/CSS dependencies from the repo and instead handles them using npm and webpack.

I hope this works because this is the first time I'm using webpack :P All of the features dependent on JS seem to work fine, but more testing would be appreciated.

~~Note that tinymce is not currently handled using webpack, I only copy the contents of the package into the output dir - I need to figure out how to get django-tinymce and tinymce plugins to cooperate, but we can handle that later (remember to make an issue when we merge this)~~ It is now, and it loads sooo much faster than when it had to load all of the plugins from separate files!

Closes #24, #267

---
This change is [Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/283)

### CODE REVIEW

**Review by cytadela8 — COMMENTED** [review]
> Reviewed 127 of 127 files at r1, 3 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/283)* status: 121 of 138 files reviewed, all discussions resolved (waiting on @cytadela8)

**Comment by krzys-h** [comment]
Rebased to fix conflict in `main.css`

**Comment by krzys-h** [comment]
Rebased again, after `forms` merge

**Review by cytadela8 — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r3, 6 of 6 files at r4, 1 of 1 files at r5, 9 of 13 files at r6.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/283)* status: 133 of 137 files reviewed, 1 unresolved discussion (waiting on @krzys-h)

___
*[templates/mydata_profilepage.html, line 19 at r6](https://reviewable.io/reviews/warsztatywww/aplikacjawww/283#-MQXXGA2AqBJIKtc1hUd:-MQXXGA2AqBJIKtc1hUe:b-vb4nd6) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/0819760af75e738c31ebe68490812086172177e5/templates/mydata_profilepage.html#L19)):*
> ```HTML
> 
> {% block script %}
>   {{ block.super }}
> ```

Why did you remove `{{block.super}}`?

**Review by krzys-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/283)* status: 133 of 137 files reviewed, 1 unresolved discussion (waiting on @cytadela8)

___
*[templates/mydata_profilepage.html, line 19 at r6](https://reviewable.io/reviews/warsztatywww/aplikacjawww/283#-MQXXGA2AqBJIKtc1hUd:-MQXYK5v-D6X5F6tE5PS:b-iibeux) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/0819760af75e738c31ebe68490812086172177e5/templates/mydata_profilepage.html#L19)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

Why did you remove `{{block.super}}`?
</blockquote></details>

I wanted to unify it as there were some places which didn't use super - only the profile page and workshop editor did it this way. Doesn't matter functionally because the block is initially empty anyway. It should probably be the other way though - all pages should use super to extend the block instead of replacing it. Should I fix that?

**Review by krzys-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/283)* status: 118 of 140 files reviewed, 1 unresolved discussion (waiting on @cytadela8)

___
*[templates/mydata_profilepage.html, line 19 at r6](https://reviewable.io/reviews/warsztatywww/aplikacjawww/283#-MQXXGA2AqBJIKtc1hUd:-MQY2Ivm4Bz2X5ziAHsO:b-896fix) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/0819760af75e738c31ebe68490812086172177e5/templates/mydata_profilepage.html#L19)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

I wanted to unify it as there were some places which didn't use super - only the profile page and workshop editor did it this way. Doesn't matter functionally because the block is initially empty anyway. It should probably be the other way though - all pages should use super to extend the block instead of replacing it. Should I fix that?
</blockquote></details>

Done.

**Review by cytadela8 — COMMENTED** [review]
I have some improvements in mind and I will submit those in a separate PR. I will approve&merge when I make necessary changes on production.

> Reviewed 20 of 21 files at r7, 6 of 6 files at r8, 1 of 1 files at r9, 14 of 14 files at r10.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/283#-:-MQc2Crf7N-iawPsMUt2:b-g8jzrv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by cytadela8 — APPROVED** [review]
:duck: 

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/283#-:-MQde8IW8JmQrlSQNFa_:bcmjph0)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
