### PR TITLE
Workshop page improv

### PR DESCRIPTION
**Pull request by cytadela8**
Replaces #497

This change is [Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/619)

### CODE REVIEW

**Review by krzys-h — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/619)* status: all files reviewed, 2 unresolved discussions (waiting on @cytadela8)

___
*[`frontend/css/custom-bootstrap.scss` line 201 at r2](https://reviewable.io/reviews/warsztatywww/aplikacjawww/619#-N9yuFDOBZK7OXfpYOwd:-N9yuFDOBZK7OXfpYOwe:bhf1vsd) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/45feb94c95d4758a626fbaf75b1b4f4147729142/frontend/css/custom-bootstrap.scss#L201)):*
> ```SCSS
> 
> .w-100 {
>   width: 100%;
> ```

This should be already defined by bootstrap...? Why is this here?
___
*[`templates/_programworkshop.html` line 10 at r2](https://reviewable.io/reviews/warsztatywww/aplikacjawww/619#-N9yuSvOCNLAmpSnIMmw:-N9yuSvOCNLAmpSnIMmx:bogsze5) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/45feb94c95d4758a626fbaf75b1b4f4147729142/templates/_programworkshop.html#L10)):*
> ```HTML
>           <h4 class="m-0">
>             {% if workshop.page_content_is_public %}
>               <a href="{% url 'workshop_page' workshop.year.pk workshop.name %}">{% endif %}
> ```

Fix this cursed indentation

**Review by cytadela8 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/619)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @krzys-h)

___
*[`frontend/css/custom-bootstrap.scss` line 201 at r2](https://reviewable.io/reviews/warsztatywww/aplikacjawww/619#-N9yuFDOBZK7OXfpYOwd:-NA0J4vN9Bf1mM5Bt15L:b-896fix) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/45feb94c95d4758a626fbaf75b1b4f4147729142/frontend/css/custom-bootstrap.scss#L201)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

This should be already defined by bootstrap...? Why is this here?
</blockquote></details>

Done.
___
*[`templates/_programworkshop.html` line 10 at r2](https://reviewable.io/reviews/warsztatywww/aplikacjawww/619#-N9yuSvOCNLAmpSnIMmw:-NA0J4SQ-F3OcUv21zEt:b-896fix) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/45feb94c95d4758a626fbaf75b1b4f4147729142/templates/_programworkshop.html#L10)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

Fix this cursed indentation
</blockquote></details>

Done.

**Review by krzys-h — CHANGES_REQUESTED** [review]
Past workshops with no short_description look kinda bad. I'm not sure what to do about this - for current program a box saying "lecturer did not add a description yet" may be fine, but none of the workshops before 2021 have descriptions:



Maybe we should check if any of the workshops have descriptions, and make the button section fill the entire screen if not? This will be kinda weird behavior in the phase just after accepting the workshops but before the lecturers have a chance to fill in the descriptions though.

---

I feel like the split point at `md` may need to be moved, because descriptions that are long (this one is exactly 140 characters, which is the limit) look weird:



If you remove the `md` split point entirely and leave only `xs` and `lg`, it looks better:



---

Other than that, I really like these changes.

> Reviewed 2 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/619#-:-NA3q7Fn98_PCyAB8PVH:baw1c3)* status: all files reviewed, 1 unresolved discussion (waiting on @cytadela8)

___
*[`templates/_programworkshop.html` line 13 at r6](https://reviewable.io/reviews/warsztatywww/aplikacjawww/619#-NA3pLnD1Z-vVhvl7qXw:-NA3pLnE9pTELVnzHd4U:b-gs1yzf) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/69c7f5f52fa0b712c7e74bbcb91de99ead74957d/templates/_programworkshop.html#L13)):*
> ```HTML
>             {% endif %}
>             {% if workshop.status == 'X' %}
>               <del>
> ```

This is still bad, why is `<del>` indented but `</del>` below is not?!

**Review by cytadela8 — COMMENTED** [review]
Maybe let's remove the md split point? As for missing short description I'm not sure what to do.

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/619#-:-NA6Tj0S56DwknwB8ele:b-ckje0z)* status: all files reviewed, 1 unresolved discussion (waiting on @krzys-h)

___
*[`templates/_programworkshop.html` line 13 at r6](https://reviewable.io/reviews/warsztatywww/aplikacjawww/619#-NA3pLnD1Z-vVhvl7qXw:-NA6TUVC8Tqis9T01wT8:b-mn4ol3) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/69c7f5f52fa0b712c7e74bbcb91de99ead74957d/templates/_programworkshop.html#L13)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

This is still bad, why is `<del>` indented but `</del>` below is not?!
</blockquote></details>

Autoformat doesn't work :/ Do you have a working auto-format?

**Review by krzys-h — CHANGES_REQUESTED** [review]
> Maybe let's remove the md split point?

Sure, please do that

> As for missing short description I'm not sure what to do.

Let's merge it as is for now and we'll worry about that later then, since this looks way better on current pages than what we had before.

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/619#-:-NA8fTAx8C4OgZwzLcGp:b9vybh7)* status: all files reviewed, 1 unresolved discussion (waiting on @cytadela8)

___
*[`templates/_programworkshop.html` line 13 at r6](https://reviewable.io/reviews/warsztatywww/aplikacjawww/619#-NA3pLnD1Z-vVhvl7qXw:-NA8fEtl4Hc1fZOvs4ym:b-glfk1l) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/69c7f5f52fa0b712c7e74bbcb91de99ead74957d/templates/_programworkshop.html#L13)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

Autoformat doesn't work :/ Do you have a working auto-format?
</blockquote></details>

I'm not even sure - I almost never use autoformat on full files because it makes a mess like this during review, if anything I use it on the code fragment I'm working on and correct it if it does something stupid like this. I think having the opening and closing tag in separate if blocks may be confusing it.

**Review by cytadela8 — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/619#-:-NB2m6sjCcnu2EMZstyC:bb6un1j)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @krzys-h)

___
*[`templates/_programworkshop.html` line 13 at r6](https://reviewable.io/reviews/warsztatywww/aplikacjawww/619#-NA3pLnD1Z-vVhvl7qXw:-NB2m4z7EPJdXO_ejHFz:b-896fix) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/69c7f5f52fa0b712c7e74bbcb91de99ead74957d/templates/_programworkshop.html#L13)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

I'm not even sure - I almost never use autoformat on full files because it makes a mess like this during review, if anything I use it on the code fragment I'm working on and correct it if it does something stupid like this. I think having the opening and closing tag in separate if blocks may be confusing it.
</blockquote></details>

Done.

**Review by krzys-h — APPROVED** [review]
> Reviewed 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/619)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
