### PR TITLE
Remove hacky owncloud integration

### LINKED ISSUE #209: Remove hacky owncloud integration after this year
see #208

### PR DESCRIPTION
**Pull request by krzys-h**
Closes #209

Merge only after owncloud is dead and merged into "internety"

---
This change is [Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/221)

### CODE REVIEW

**Review by cytadela8 — APPROVED** [review]
> Reviewed 6 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/221)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by cytadela8 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/221#-:-MFCiyn92oy0IcDO8GWj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by cytadela8 — APPROVED** [review]
We no longer need the owncloud integration, can you rebase?

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/221#-:-MFWXo7R4S_vZ7oA7MEy:b-yg0myp)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by krzys-h — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/221#-:-MFXGF6g0YSn208nPSuC:bb6un1j)* status: 2 of 7 files reviewed, all discussions resolved (waiting on @cytadela8)

**Review by cytadela8 — APPROVED** [review]
> Reviewed 5 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/221)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by cytadela8 — CHANGES_REQUESTED** [review]
Sorry, please also rebase on top of current code to grant AGPL v3 licence.

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/221#-:-MHEkigC87AY7V9kT4Xl:b-ac0wn)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by cytadela8 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/221)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
