### PR TITLE
Implement solution uploads

### PR DESCRIPTION
**Pull request by krzys-h**
### Solution editor
screencapture-localhost-8000-2021-workshop-testing-solution-2021-01-30-00_18_04

### Lecturer view
image
(don't mind the missing icon from #326 :P)

the "Open solution" button opens a view identical to the participant one but read-only and without the long description at the top

### Links to solution submission
image
image
image
Note that the buttons appear only if you are registered for the workshop... I'm not sure I like that from an UX perspective. Maybe the user should get auto-registered on submit instead if they haven't done so before?

### TODO
* Edit history or no edit history?
* Are the locations of the send solution buttons good? Any better ideas?
* More manual testing
* More automated testing

---
This change is [Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/328)

### CODE REVIEW

**Comment by krzys-h** [comment]
Before I forget: remember to block /media/solutions in nginx!!!

**Review by krzys-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/328)* status: 0 of 18 files reviewed, 1 unresolved discussion

___
*[wwwapp/models.py, line 420 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/328#-MSFXp2m6ho7KDbJ7Wj6:-MSFXp2nBj14YPBpJDaD:b-se3qyc) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/8cafa88439ac81cf1fb0cf4de01447b8a2d80a1c/wwwapp/models.py#L420)):*
> ```Python
>     workshop_participant = instance.solution.workshop_participant
>     # TODO: hash the file?
>     return f'solutions/{workshop_participant.workshop.name}/{workshop_participant.participant.user.pk}/{filename}'
> ```

This path should include the workshop year..,

**Review by cytadela8 — COMMENTED** [review]
Splitting into more commits would make reviews easier :/ The TODO you wrote needs to be done before merging. I will look how stuff works and looks later.

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/328#-:-MSHw2ehC-iB22chzmTL:b-fly4bd)* status: 0 of 18 files reviewed, 1 unresolved discussion

**Review by krzys-h — COMMENTED** [review]
> Splitting into more commits would make reviews easier

Done

> The TODO you wrote needs to be done before merging.

It's not THAT important. Django ensures uniqueness of the names already, and these files are not directly accessible from `/media` == not cached.

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/328#-:-MSI5CmC65LbqAlPZ3qB:bubydmm)* status: 0 of 18 files reviewed, all discussions resolved

**Review by cytadela8 — COMMENTED** [review]
> It's not THAT important. Django ensures uniqueness of the names already, and these files are not directly accessible from /media == not cached.
But we definitely need more tests than what was at r1. I also want too look into how storage works, because I don't like making exceptions to what is hosted by Nxinx. There should be a separate directory for public no-auth files and private hosted by Django.

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/328#-:-MSIAQWt1yO0jQA1S16B:b-foxygw)* status: 0 of 18 files reviewed, all discussions resolved

**Review by krzys-h — COMMENTED** [review]
> But we definitely need more tests than what was at r1.

True. I will probably be writing more tests later (I hate writing tests :<).

> I also want too look into how storage works, because I don't like making exceptions to what is hosted by Nxinx.

Actually, that seems doable. I didn't think to check earlier, but you can define a separate directory for a specific FileField. We should also move qual problems there, as they are never accessed through /media directly either.

It would also be a good idea to use X-Sendfile instead of hosting the files through Django, but I need to look into how to set that up for this to work both in prod and dev environments.

https://stackoverflow.com/questions/1729051/django-upload-to-outside-of-media-root

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/328#-:-MSIHklC04BBywvoKN29:b-ylrlbc)* status: 0 of 18 files reviewed, all discussions resolved

**Review by krzys-h — COMMENTED** [review]
> Note that the buttons appear only if you are registered for the workshop... I'm not sure I like that from an UX perspective. Maybe the user should get auto-registered on submit instead if they haven't done so before?

I made the buttons appear always (if the workshop is qualifying and after tasks are available), but disabled with a tooltip until you register.

> It would also be a good idea to use X-Sendfile instead of hosting the files through Django, but I need to look into how to set that up for this to work both in prod and dev environments.

Done. Nginx implements it slightly differently than apache with `X-Sendfile`, it uses a header named `X-Accel-Redirect` and it's value is an URL rather than a file path. Note that you will need to set `SENDFILE_ROOT` in `local_settings.py` to be equal to `MEDIA_ROOT`. No changes to nginx config should be needed until we separate the directories as we already have `/media` set up.

>> I also want too look into how storage works, because I don't like making exceptions to what is hosted by Nxinx.
>
> Actually, that seems doable. I didn't think to check earlier, but you can define a separate directory for a specific FileField. We should also move qual problems there, as they are never accessed through /media directly either.

Done. You will also have to update `SENDFILE_ROOT` to point to the uploads directory on the server. You will also have to move `/media/qualification` to `/uploads/qualification` manually after migration. You will also need to add the uploads directory to the nginx config, with the `internal;` directive to ensure that they can only be served by Django using `X-Accel-Redirect` and not externally. Do not enable caching on that directory (I did not test it and it may forward the caching headers to the Django endpoints which would be bad)

>> But we definitely need more tests than what was at r1.
>
> True. I will probably be writing more tests later (I hate writing tests :<).

Not done (yet...)

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/328#-:-MSJiEnc1VqbtgD_T92Z:b-9wn5yj)* status: 0 of 30 files reviewed, all discussions resolved

**Review by krzys-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/328)* status: 0 of 30 files reviewed, 1 unresolved discussion

___
*[wwwapp/migrations/0072_change_upload_storage.py, line 18 at r10](https://reviewable.io/reviews/warsztatywww/aplikacjawww/328#-MSJo-wQ6qE_rsJaKlcV:-MSJo-wRCnmnPh92ytQz:b2t17tg) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/c958d225bd0e54735d67101d9479e6031f6e140e/wwwapp/migrations/0072_change_upload_storage.py#L18)):*
> ```Python
>             model_name='solutionfile',
>             name='file',
>             field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/uploads/', location='/home/krzys_h/Pulpit/aplikacjawww/uploads'), upload_to=wwwapp.models.solutions_dir, verbose_name='Plik'),
> ```

WTF Django?! I have no idea how to fix this...

**Review by cytadela8 — COMMENTED** [review]
TODO (not necesserly in this PR):
- progress bar for uploads
- grading on the page with solution download

> Reviewed 1 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/328#-:-MSKzE6p85Mhhy8DozSX:b-z6nisy)* status: 0 of 30 files reviewed, 1 unresolved discussion (waiting on @cytadela8)

**Review by cytadela8 — COMMENTED** [review]
- add field for "how to submit" info if solutions not submitted through website

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/328#-:-MSKztqC77XoP_Yb1Mc4:bqfzty2)* status: 0 of 30 files reviewed, 1 unresolved discussion (waiting on @cytadela8)

**Review by krzys-h — COMMENTED** [review]
> progress bar for uploads

I don't think anybody is going to be uploading files so big for that to be necessary... Speaking of which, do we need a size limit?

> grading on the page with solution download

Would be nice to have, but we can implement that later

> add field for "how to submit" info if solutions not submitted through website

I don't expect submitting outside of the website to be a common option so I don't think we should even bother. I mostly just needed a flag to differentiate between old and now options in the grades UI (because for old workshops grading without uploaded solution is allowed and for new ones its not), so I just made it a feature instead in case we ever need it.

>>> But we definitely need more tests than what was at r1.
>>
>> True. I will probably be writing more tests later (I hate writing tests :<).
>
> Not done (yet...)

Working on it...

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/328#-:-MUFHWUP1ZmQ9-1Hyp54:b-550rrw)* status: 0 of 30 files reviewed, all discussions resolved (waiting on @cytadela8)

___
*[wwwapp/migrations/0072_change_upload_storage.py, line 18 at r10](https://reviewable.io/reviews/warsztatywww/aplikacjawww/328#-MSJo-wQ6qE_rsJaKlcV:-MUFHQqG9fsUYU_t8KCa:b-886gsx) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/c958d225bd0e54735d67101d9479e6031f6e140e/wwwapp/migrations/0072_change_upload_storage.py#L18)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

WTF Django?! I have no idea how to fix this...
</blockquote></details>

Fixed

**Review by krzys-h — COMMENTED** [review]
I finally added some tests. There are probably more things that could be tested, but meh.

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/328#-:-MUFeoLQCPkTx7umEH0v:b3sxbqk)* status: 0 of 31 files reviewed, all discussions resolved (waiting on @cytadela8)

**Review by cytadela8 — CHANGES_REQUESTED** [review]
Updated TODO:
- Merge migrations (remove new ones and regenerate)
- limit upload size. We definitially need some limit... Some limit might be already enforced by nginx.

I have only the test file left to review

> Reviewed 3 of 18 files at r1, 17 of 17 files at r2, 4 of 4 files at r3, 29 of 29 files at r11, 4 of 4 files at r12, 5 of 5 files at r13, 2 of 2 files at r14, 2 of 2 files at r15, 6 of 6 files at r16, 6 of 6 files at r17, 6 of 6 files at r18, 9 of 9 files at r19.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/328#-:-MSwclTq7yGQtvypKgZ-:bxuf4ti)* status: 30 of 31 files reviewed, 2 unresolved discussions (waiting on @krzys-h)

___
*[Dockerfile, line 38 at r17](https://reviewable.io/reviews/warsztatywww/aplikacjawww/328#-MUJAdOZ88CooPqfChjn:-MUJAdOZ88CooPqfChjo:bwyd1l) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/f4c900b906c9b6721f2ac8438de61dd12823d9b9/Dockerfile#L38)):*
> ```Dockerfile
> 
> CMD gunicorn wwwapp.wsgi:application --bind 0.0.0.0:8000
> ENTRYPOINT ["./entrypoint.sh"]
> ```

Fun fact, I also have a dockerfile locally :laughing: Although this is much better.
___
*[templates/_qualificationsTable.html, line 19 at r16](https://reviewable.io/reviews/warsztatywww/aplikacjawww/328#-MUJ8hUsDuZWx2QdlW94:-MUJ8hUsDuZWx2QdlW95:b-55hwyf) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/56cc9d069f308ad0beed4f45f48b1b16bd4f3c87/templates/_qualificationsTable.html#L19)):*
> ```HTML
>           </a>
>         </th>
>         {% if not workshop_participant.solution and workshop_participant.workshop.are_solutions_editable and workshop_participant.workshop.solution_uploads_enabled and workshop_participant.workshop.is_qualifying and workshop_participant.workshop.qualification_problems %}
> ```

This looks horrible. Can we do anything about it? At least add a coment what's going on here.
___
*[templates/workshoppage.html, line 30 at r16](https://reviewable.io/reviews/warsztatywww/aplikacjawww/328#-MUJ9STB954Sxxu_nQMw:-MUJ9STB954Sxxu_nQMx:b-8hv32m) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/56cc9d069f308ad0beed4f45f48b1b16bd4f3c87/templates/workshoppage.html#L30)):*
> ```HTML
>     <span class="d-inline-block enable-tooltip"
>         {# this wrapper div is here to allow the tooltip to work on a disabled element, see https://getbootstrap.com/docs/4.0/components/tooltips/#disabled-elements #}
>         {% if not registered %}data-toggle="tooltip" data-placement="right" title="Przed przesłaniem rozwiązań, zapisz się na warsztaty"{% endif %}
> ```

BTW, we should add some buttons to register on workshop page.
___
*[wwwapp/views.py, line 674 at r13](https://reviewable.io/reviews/warsztatywww/aplikacjawww/328#-MUIg0IN38n9RmfruKwK:-MUIg0IN38n9RmfruKwL:b5vf24f) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/e17629c659a4e95978a960e36dd9f24875dd89bf/wwwapp/views.py#L674)):*
> ```Python
>         return HttpResponseForbidden("Warsztaty nie zostały zaakceptowane")
>     if not workshop.is_qualifying:
>         raise Http404('Na te warsztaty nie obowiązuje kwalifikacja')
> ```

Minor, All of this should probably be HttpResponseForbidden

**Review by krzys-h — COMMENTED** [review]
> Merge migrations (remove new ones and regenerate)

I'm not 100% sure what is going to happen if you have two AlterField statements for the same field in one migration. Currently, the `solution_uploads_enabled` is first created with `default=False` (to apply this value to all existing workshops) and then is immediately changed to `default=True` (for new workshops).

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/328#-:-MUJDbgr-AOVssEUyweA:bhf035n)* status: 30 of 31 files reviewed, 2 unresolved discussions (waiting on @cytadela8 and @krzys-h)

___
*[templates/_qualificationsTable.html, line 19 at r16](https://reviewable.io/reviews/warsztatywww/aplikacjawww/328#-MUJ8hUsDuZWx2QdlW94:-MUJEvWW0oNRn6J9zucT:b-qqnrwd) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/56cc9d069f308ad0beed4f45f48b1b16bd4f3c87/templates/_qualificationsTable.html#L19)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

This looks horrible. Can we do anything about it? At least add a coment what's going on here.
</blockquote></details>

This is basically "you have not uploaded a solution and you are allowed to upload a solution". Everywhere else, these conditions are spread apart in nested ifs, they just so happened to all be required for the table.

I guess I can add `workshop_participant.can_edit_solution` which checks the entire "you are allowed to upload a solution" part in one go, but this requires refactoring in other places to keep it consistent.
___
*[templates/workshoppage.html, line 30 at r16](https://reviewable.io/reviews/warsztatywww/aplikacjawww/328#-MUJ9STB954Sxxu_nQMw:-MUJG2TvD2-j-RTYKszL:bkyupqh) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/56cc9d069f308ad0beed4f45f48b1b16bd4f3c87/templates/workshoppage.html#L30)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

BTW, we should add some buttons to register on workshop page.
</blockquote></details>

Add that to the issues list, this PR is big enough already
___
*[wwwapp/views.py, line 674 at r13](https://reviewable.io/reviews/warsztatywww/aplikacjawww/328#-MUIg0IN38n9RmfruKwK:-MUJEe1E9wxbyAu0HjuR:bbwh6x9) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/e17629c659a4e95978a960e36dd9f24875dd89bf/wwwapp/views.py#L674)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

Minor, All of this should probably be HttpResponseForbidden
</blockquote></details>

I'm not sure. We use 404 in qualification tasks view when qualification is disabled.

**Review by krzys-h — COMMENTED** [review]
>> Merge migrations (remove new ones and regenerate)
> 
> I'm not 100% sure what is going to happen if you have two AlterField statements for the same field in one migration. Currently, the solution_uploads_enabled is first created with default=False (to apply this value to all existing workshops) and then is immediately changed to default=True (for new workshops).

Done. It works as expected.

> limit upload size. We definitially need some limit... Some limit might be already enforced by nginx.

Thinking about it, it doesn't really make sense to limit the upload size on Django side. If you go over the nginx limit, the request won't even get to Django anyway, if you make the nginx limit greater than the Django one, Django may store the uploaded file in `/tmp` before we get to process it so why not just let the user store it at that point.

> Dismissed @cytadela8 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/328#-:-MUJtkgQ2CyuLOda3A5x:bc9dl7y)* status: 22 of 29 files reviewed, all discussions resolved (waiting on @cytadela8)

___
*[templates/_qualificationsTable.html, line 19 at r16](https://reviewable.io/reviews/warsztatywww/aplikacjawww/328#-MUJ8hUsDuZWx2QdlW94:-MUJsj3Q-VtfbnCpipZx:b-896fix) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/56cc9d069f308ad0beed4f45f48b1b16bd4f3c87/templates/_qualificationsTable.html#L19)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

This is basically "you have not uploaded a solution and you are allowed to upload a solution". Everywhere else, these conditions are spread apart in nested ifs, they just so happened to all be required for the table.

I guess I can add `workshop_participant.can_edit_solution` which checks the entire "you are allowed to upload a solution" part in one go, but this requires refactoring in other places to keep it consistent.
</blockquote></details>

Done.

**Review by cytadela8 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r20, 6 of 6 files at r21, 3 of 3 files at r22.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/328)* status: all files reviewed, 3 unresolved discussions (waiting on @krzys-h)

___
*[templates/program.html, line 59 at r21](https://reviewable.io/reviews/warsztatywww/aplikacjawww/328#-MUK3kgc6BX6cwJLRq4i:-MUK3kgc6BX6cwJLRq4j:b-ydoxws) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/9a7a591fffc9bd524ba81e308424e81a91d1fe05/templates/program.html#L59)):*
> ```HTML
>                         <a href="{% url 'qualification_problems' workshop.year.pk workshop.name %}" class="mr-3"> Link </a>
> 
>                         {% if workshop.can_access_solution_upload and workshop.are_solutions_editable %}
> ```

What if user is not registered and registers without refreshing the page?
The button will still be disabled!!!

___
*[templates/program.html, line 67 at r21](https://reviewable.io/reviews/warsztatywww/aplikacjawww/328#-MUK3TNkCfizkrr9NN9R:-MUK3TNkCfizkrr9NN9S:bdspyq) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/9a7a591fffc9bd524ba81e308424e81a91d1fe05/templates/program.html#L67)):*
> ```HTML
>                                class="btn btn-primary btn-sm {% if not registered %}disabled{% endif %}"
>                                href="{% url 'workshop_my_solution' workshop.year.pk workshop.name %}">
>                               <i class="fas fa-paper-plane"></i> Prześlij rozwiązania!
> ```

This button makes whole workshop higher and things don't look so good

___
*[templates/program.html, line 67 at r21](https://reviewable.io/reviews/warsztatywww/aplikacjawww/328#-MUK6jxFC0qamuGBXCiv:-MUK6jxFC0qamuGBXCiw:b-83yjqd) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/9a7a591fffc9bd524ba81e308424e81a91d1fe05/templates/program.html#L67)):*
> ```HTML
>                                class="btn btn-primary btn-sm {% if not registered %}disabled{% endif %}"
>                                href="{% url 'workshop_my_solution' workshop.year.pk workshop.name %}">
>                               <i class="fas fa-paper-plane"></i> Prześlij rozwiązania!
> ```

Also what is this on mobile

**Review by krzys-h — COMMENTED** [review]
> Dismissed @cytadela8 from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/328)* status: 24 of 30 files reviewed, all discussions resolved (waiting on @cytadela8)

___
*[templates/program.html, line 59 at r21](https://reviewable.io/reviews/warsztatywww/aplikacjawww/328#-MUK3kgc6BX6cwJLRq4i:-MUKN7kJ9m4KEwJHAq_u:b-896fix) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/9a7a591fffc9bd524ba81e308424e81a91d1fe05/templates/program.html#L59)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

What if user is not registered and registers without refreshing the page?
The button will still be disabled!!!


</blockquote></details>

Done.
___
*[templates/program.html, line 67 at r21](https://reviewable.io/reviews/warsztatywww/aplikacjawww/328#-MUK3TNkCfizkrr9NN9R:-MUKN8ylCjSIgbayJW4a:bh2j48y) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/9a7a591fffc9bd524ba81e308424e81a91d1fe05/templates/program.html#L67)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

This button makes whole workshop higher and things don't look so good


</blockquote></details>

Done. I decreased the margins.
___
*[templates/program.html, line 67 at r21](https://reviewable.io/reviews/warsztatywww/aplikacjawww/328#-MUK6jxFC0qamuGBXCiv:-MUKNC0K5gj-TF3XLYfF:b-x88mea) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/9a7a591fffc9bd524ba81e308424e81a91d1fe05/templates/program.html#L67)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

Also what is this on mobile


</blockquote></details>

Done. I replaced "link" with a button and shortened the text.

**Review by cytadela8 — APPROVED** [review]
:duck: :duck: :duck: 

> Reviewed 3 of 3 files at r23, 4 of 4 files at r24.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/328#-:-MUKci2E9o3hPeuOIdcg:b-eli7ho)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
