### PR TITLE
Dynamic forms system

### LINKED ISSUE #152: Improve UserInfo handling
After #150, it will be possible to make UserInfo optional. This will make it possible to improve our handling of this data, which so far was simply "clear all the fields manually between editions"

* Make UserInfo truly optional - as in `UserInfo.objects.all().delete()` should remove the data and recreate the objects when needed, not break everything
* Add a warning if you forget to remove UserInfo for the previous edition when changing settings.CURRENT_YEAR, and possibly provide a way to automate it
* Unlock the UserInfo tab in the profile only when the user qualifies for the workshops. The objects shouldn't exist at all if not. That's why it was a separate thing in the first place.

This would also fix #131 as a change to year settings would imply clearing old data

### PR DESCRIPTION
**Pull request by krzys-h**
This is a work in progress forms system to satisfy requirements of #260.

* User info form is no longer hardcoded - it's fully configurable in Django admin
* Multiple forms can be defined - so they can be used not only for user info, but also for t-shirt shipping, surveys after workshops etc.
* Questions in a form can be marked as required
* Every question in a form can be independently locked from further editing
* Every answer has an independent "last changed" timestamp
* All answers for one question or entire form can be easily cleared (forcing people to fill them out again in the next edition to prevent stale data, and removing personal info which we should not be keeping for longer than one edition - also closes #152 and #131)
* Results of all forms are displayed in the participants, lecturers and all people data tables. A new "form results" view is also provided.
* UserInfo was removed in favor of a form. All current data is migrated.

As is, this fits the first 3 requirements in #260, 4th one is partial (you can't save the form if some of the required information is missing, but there is nothing pointing you to the form letting you know that you have to fill it in) and managing access will be implemented when I figure out how I want to do it.

screencapture-localhost-8000-admin-wwwforms-form-1-change-2021-01-02-23_22_19

TODO:
* [x] Add support for `<select>` choice fields
* [ ] Add support for more field types (1-10 rating for surveys, regex, and other things I may think of later)
* [x] Write tests
* [x] View with a list of all forms under Admin and links to the results view
* [ ] Make it possible to control visibility to participants and lecturers. Currently, all logged in users can fill out forms.
* [x] Make the list of available forms better (after #269 probably)

---
This change is [Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/272)

### CODE REVIEW

**Review by cytadela8 — COMMENTED** [review]
Few things to note:
- I see space for data processing improvements (frequently you use filter to find specific element in array resulting in total square time, but this shouldn't be a problem)
- Maybe it would be better to treat start and end date fields to be different type?

I will finish review another day

> Reviewed 15 of 15 files at r1, 5 of 5 files at r2, 2 of 2 files at r3, 5 of 5 files at r4, 7 of 14 files at r5.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/272#-:-MQ7wMRkB7YJIcPA_sZG:b-ogysj4)* status: 17 of 33 files reviewed, 2 unresolved discussions (waiting on @cytadela8 and @krzys-h)

___
*[wwwapp/auth.py, line 38 at r5](https://reviewable.io/reviews/warsztatywww/aplikacjawww/272#-MQ7xZ6-2k3lyWm5UiQk:-MQ7xZ6-2k3lyWm5UiQl:befsz60) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/ca7cdd60998a50247f7d433ba6dbfc194203fec0/wwwapp/auth.py#L38)):*
> ```Python
>     # Make sure to call get_context after UserProfile gets created, since it is required
>     # to figure out what to show on the menu bar
>     context = get_context(request)
> ```

Minor, will this even work as expected with our context_processors? I'm not sure what's called first. Also the UserProfile creation can be probably removed. I think we can safely assume there are no broken users and if there are we will fix that manually when found.
___
*[wwwforms/forms.py, line 8 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/272#-MQ7rBhZ5SfVCxFKOL_D:-MQ7rBhZ5SfVCxFKOL_E:b24tcns) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/5897f624feadd3a627125c3fb98220ebcf86daa5/wwwforms/forms.py#L8)):*
> ```Python
> 
> from wwwapp.models import Camp
> from wwwforms.models import FormQuestion, FormQuestionAnswer, pesel_validate, Form
> ```

Minor. For clerity can you _not_ import `Form`, but refer to it where needed by `wwwforms.models.Form`

**Review by krzys-h — COMMENTED** [review]
> I see space for data processing improvements (frequently you use filter to find specific element in array resulting in total square time, but this shouldn't be a problem)

The main performance bottleneck is SQL queries, so avoiding running more queries than necessary and doing it in Python instead was more important. I will improve it later if it becomes a problem.

> Maybe it would be better to treat start and end date fields to be different type?

I considered this initially, but it creates more problems than it solves - you have to ensure that they can be added at most once, otherwise the "start is earlier than end" validation becomes very ambiguous

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/272#-:-MQ84F_yEPEQUM8Na-O3:bf1mchz)* status: 17 of 33 files reviewed, 2 unresolved discussions (waiting on @cytadela8 and @krzys-h)

___
*[wwwapp/auth.py, line 38 at r5](https://reviewable.io/reviews/warsztatywww/aplikacjawww/272#-MQ7xZ6-2k3lyWm5UiQk:-MQ83dmZAGQ2GG4qi4iW:bi9z8yx) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/ca7cdd60998a50247f7d433ba6dbfc194203fec0/wwwapp/auth.py#L38)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

Minor, will this even work as expected with our context_processors? I'm not sure what's called first. Also the UserProfile creation can be probably removed. I think we can safely assume there are no broken users and if there are we will fix that manually when found.
</blockquote></details>

My bad, I forgot about the auth views. This context will override the context processor one, but SQL queries get executed twice.

**Review by krzys-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/272)* status: 7 of 33 files reviewed, 1 unresolved discussion (waiting on @cytadela8 and @krzys-h)

___
*[wwwapp/auth.py, line 38 at r5](https://reviewable.io/reviews/warsztatywww/aplikacjawww/272#-MQ7xZ6-2k3lyWm5UiQk:-MQ88M6O9VYj8-BFaxsH:b-886gsx) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/ca7cdd60998a50247f7d433ba6dbfc194203fec0/wwwapp/auth.py#L38)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

My bad, I forgot about the auth views. This context will override the context processor one, but SQL queries get executed twice.
</blockquote></details>

Fixed

**Review by cytadela8 — COMMENTED** [review]
OK!

> Reviewed 22 of 22 files at r6, 5 of 5 files at r7, 2 of 2 files at r8, 5 of 5 files at r9, 6 of 13 files at r10.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/272#-:-MQ8H9bN18m_VwyHE-tb:b2nhktc)* status: 17 of 33 files reviewed, 1 unresolved discussion (waiting on @cytadela8 and @krzys-h)

**Review by cytadela8 — COMMENTED** [review]
> Reviewed 21 of 22 files at r11, 5 of 5 files at r12, 2 of 2 files at r13, 5 of 5 files at r14, 14 of 16 files at r15, 5 of 5 files at r16, 4 of 4 files at r17, 7 of 7 files at r18, 4 of 4 files at r19, 5 of 5 files at r20, 4 of 4 files at r21.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/272)* status: 41 of 42 files reviewed, 2 unresolved discussions (waiting on @cytadela8 and @krzys-h)

___
*[wwwforms/models.py, line 58 at r20](https://reviewable.io/reviews/warsztatywww/aplikacjawww/272#-MQ9TFbj1Ekcdn9EmzDN:-MQ9TFbj1Ekcdn9EmzDO:b1l209c) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/02a225e58a72e12577325f34e0711b388ba5712f/wwwforms/models.py#L58)):*
> ```Python
>     name = models.SlugField(max_length=50, blank=False, unique=True, verbose_name='Nazwa', help_text='(w URLach)')
>     title = models.CharField(max_length=50, blank=False, verbose_name='Tytuł')
>     description = models.CharField(max_length=1000, blank=True, verbose_name='Opis', help_text='Krótki opis wyświetlany na górze formulaza')
> ```

Why not `TextField`? I don't like arbitrary limits.

**Review by krzys-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/272)* status: 41 of 42 files reviewed, 2 unresolved discussions (waiting on @cytadela8 and @krzys-h)

___
*[wwwforms/models.py, line 58 at r20](https://reviewable.io/reviews/warsztatywww/aplikacjawww/272#-MQ9TFbj1Ekcdn9EmzDN:-MQ9uuAjBqRz3F_Re3yr:b-heri5k) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/02a225e58a72e12577325f34e0711b388ba5712f/wwwforms/models.py#L58)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

Why not `TextField`? I don't like arbitrary limits.
</blockquote></details>

Mostly because all other things in the app use CharField, but I do agree that TextField would probably be a better choice here (and everywhere else...)

**Review by krzys-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/272)* status: 7 of 42 files reviewed, 2 unresolved discussions (waiting on @cytadela8 and @krzys-h)

___
*[wwwforms/models.py, line 58 at r20](https://reviewable.io/reviews/warsztatywww/aplikacjawww/272#-MQ9TFbj1Ekcdn9EmzDN:-MQ9y0vD-3EW3Mt-YlRE:b-5sshus) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/02a225e58a72e12577325f34e0711b388ba5712f/wwwforms/models.py#L58)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

Mostly because all other things in the app use CharField, but I do agree that TextField would probably be a better choice here (and everywhere else...)
</blockquote></details>

uhh actually those were TextFields with max_length still set for some reason - fixed

**Review by cytadela8 — COMMENTED** [review]
Later, before merging, I will ask you to consolidate the migrations. 

> Reviewed 26 of 35 files at r22, 4 of 5 files at r23, 1 of 2 files at r24, 4 of 5 files at r25, 12 of 16 files at r26, 3 of 5 files at r27, 3 of 7 files at r29, 2 of 4 files at r30, 1 of 5 files at r31.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/272#-:-MQE1X9ZE2tMKdgnW-VR:b-h4allm)* status: 28 of 42 files reviewed, 1 unresolved discussion (waiting on @cytadela8 and @krzys-h)

**Comment by krzys-h** [comment]
Okay, I think that's enough features for one PR - we can expand it with things like participant/lecturer permissions later

**Review by cytadela8 — CHANGES_REQUESTED** [review]
Please squash migrations. We are missing tests for some form data types (choice, select and multichoice), but that's kind of ok. If you find time it would be nice to add an migration test, but we didn't test migrations before so it's kind of fine to just see if anything breaks on production  We have backups. 

> Reviewed 1 of 16 files at r26, 2 of 5 files at r27, 3 of 4 files at r28, 3 of 7 files at r29, 2 of 4 files at r30, 4 of 5 files at r31, 4 of 4 files at r32, 8 of 8 files at r33, 3 of 3 files at r34.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/272#-:-MQUXxVG2qRipClKQblW:b7309ji)* status: all files reviewed, 2 unresolved discussions (waiting on @krzys-h)

___
*[wwwforms/forms.py, line 106 at r34](https://reviewable.io/reviews/warsztatywww/aplikacjawww/272#-MQUUS4lBcvqt2sfR9Wm:-MQUUS4lBcvqt2sfR9Wn:bldf2lm) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/ad1e512d8b49b40abe15d221904dd46f6a46b869/wwwforms/forms.py#L106)):*
> ```Python
> 
>             if self.cleaned_data[arrival_date_field]:
>                 if self.cleaned_data[arrival_date_field] < current_year.start_date:
> ```

Right hand side may be Null (we allow a camp to not have set the start and end dates)

**Review by krzys-h — COMMENTED** [review]
> Please squash migrations.

Done.

> We are missing tests for some form data types (choice, select and multichoice), but that's kind of ok.

I will add it to the big list of things that should be tested but are not... (#257) I got tired of writing tests :P

> If you find time it would be nice to add an migration test, but we didn't test migrations before so it's kind of fine to just see if anything breaks on production 

I don't think there is much point to migration tests in our case. We are going to use it only once so it's useless for regression testing, and it's not going to magically make me realize there is an edge case in the prod database I didn't think of.

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/272#-:-MQW_rTyAzE4HOfh4phX:b-z5ahqk)* status: 6 of 36 files reviewed, 1 unresolved discussion (waiting on @cytadela8)

___
*[wwwforms/forms.py, line 106 at r34](https://reviewable.io/reviews/warsztatywww/aplikacjawww/272#-MQUUS4lBcvqt2sfR9Wm:-MQWaILK17YFuzu5qNoy:bei6nbq) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/ad1e512d8b49b40abe15d221904dd46f6a46b869/wwwforms/forms.py#L106)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

Right hand side may be Null (we allow a camp to not have set the start and end dates)
</blockquote></details>

Interesting... I copied this from the old UserInfo form. I think the original assumption here was that the start/end dates are not set only for the old workshops right after migration (other than the current thanks to WORKSHOPS_START_DATE) and this always uses the latest one. Fixed anyway.

**Comment by krzys-h** [comment]
Rebased after `style-improv` merge

**Review by cytadela8 — APPROVED** [review]
:duck: 

> Reviewed 38 of 38 files at r35, 6 of 6 files at r36, 5 of 5 files at r37, 2 of 2 files at r38, 5 of 5 files at r39, 16 of 16 files at r40, 5 of 5 files at r41, 4 of 4 files at r42, 7 of 7 files at r43, 4 of 4 files at r44, 5 of 5 files at r45, 4 of 4 files at r46, 8 of 8 files at r47, 3 of 3 files at r48, 11 of 11 files at r49.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/272#-:-MQXGdgY2lHiPm_sGDcJ:bcmjph0)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
