### PR TITLE
Add some tests

### LINKED ISSUE #35: Unitests
UNIT TEST EVERYTHING UGABUGA

### PR DESCRIPTION
**Pull request by krzys-h**
Finally, some tests. This obviously doesn't cover everything, but at least it's something. I split the tests into 3 categories:
* `test_workshop_edit`: Everything related to submitting workshop proposals and publishing the workshop pages
* `test_workshop_qualification`: Everything related to users browsing the program, registering for workshops, and getting grades from lecturers
* `test_camp_qualification`: Everything related to users getting accepted into the camp, including filling out their profile

For now I focused on things that the end users (participants and lecturers) are interacting with, so the admin-only lists of people etc. are not fully covered yet

Closes #35

Oh, and I fixed a few minor bugs that I found while writing the tests, most importantly the IntegrityError that happened if participants tried to edit the workshop registration using multiple tabs.

---
This change is [Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/234)

### CODE REVIEW

**Review by cytadela8 — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/234#-:-MFBUmPHBAjmW-kI5m7T:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @krzys-h)

___
*[wwwapp/tests/test_camp_qualification.py, line 18 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/234#-MFBUnzqBBcC_vYmWL-b:-MFBUnzqBBcC_vYmWL-c:b-49vhau) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/b242db339e8ac5a2d04fc7d18d6821cb132eb810/wwwapp/tests/test_camp_qualification.py#L18)):*
> ```Python
>     CURRENT_YEAR=2020,
>     WORKSHOPS_START_DATE=datetime.date(2020, 7, 3),
>     WORKSHOPS_END_DATE=datetime.date(2020, 7, 15)
> ```

Will this break after merging #230?
___
*[wwwapp/tests/test_workshop_edit.py, line 74 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/234#-MFBTPvqEAAisxdl2Fra:-MFBTPvqEAAisxdl2Frb:b-7g0cld) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/b242db339e8ac5a2d04fc7d18d6821cb132eb810/wwwapp/tests/test_workshop_edit.py#L74)):*
> ```Python
>         self.assertContains(response, 'This type 1')
>         self.assertContains(response, 'This type 2')
>         self.assertContains(response, 'This category 1')
> ```

Minor, It would be good to not hardcode any strings. (if you define category name in one place, you should use a variable to reference it in other)

**Review by krzys-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/234)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @cytadela8)

___
*[wwwapp/tests/test_camp_qualification.py, line 18 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/234#-MFBUnzqBBcC_vYmWL-b:-MFBWTbe3WwYWVKXQOMl:b1r2vs0) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/b242db339e8ac5a2d04fc7d18d6821cb132eb810/wwwapp/tests/test_camp_qualification.py#L18)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

Will this break after merging #230?
</blockquote></details>

It will, but my point was to test #230 using this. The changes required will not be too big.
___
*[wwwapp/tests/test_workshop_edit.py, line 74 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/234#-MFBTPvqEAAisxdl2Fra:-MFBWv8EB-LrrK6gXE90:b-wpg13r) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/b242db339e8ac5a2d04fc7d18d6821cb132eb810/wwwapp/tests/test_workshop_edit.py#L74)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

Minor, It would be good to not hardcode any strings. (if you define category name in one place, you should use a variable to reference it in other)
</blockquote></details>

Probably... but I don't think it makes that much of a difference

**Review by cytadela8 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/234#-:-MFBbld17Eu6X5B-1JwY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[wwwapp/views.py, line 127 at r2](https://reviewable.io/reviews/warsztatywww/aplikacjawww/234#-MFBaFz55DQL3THcXeVI:-MFBaFz55DQL3THcXeVJ:blw8t2e) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/c821218d7b32658df3d5a6eb0fc06ba810076617/wwwapp/views.py#L127)):*
> ```Python
>     if request.method == 'POST':
>         if not request.user.is_authenticated:
>             return redirect_to_login(reverse('profile', args=[user_id]))
> ```

Hmm, this is not ideal. I sense somebody may lose data if he/she gets logged out while editing their profile. I created #235

**Comment by krzys-h** [comment]
___
*[wwwapp/views.py, line 127 at r2](https://reviewable.io/reviews/warsztatywww/aplikacjawww/234#-MFBaFz55DQL3THcXeVI:-MFBczvrCOFC2j_F4ZWz:b-pwrbpz) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/c821218d7b32658df3d5a6eb0fc06ba810076617/wwwapp/views.py#L127)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

Hmm, this is not ideal. I sense somebody may lose data if he/she gets logged out while editing their profile. I created #235 
</blockquote></details>

This is not the profile editor, this is the admin clicking the accept/reject button on the profile page - but true, the profile editor has the same problem

**Pull request merged**
