### PR TITLE
Remove the responsive DataTables plugin

### LINKED ISSUE #201: DataTables should be usable on mobile
Current solution for tables (DataTables) is barely usable on mobile it's "responsivnes" frequently hides all columns by one. It's hard to sort by an column and see the same data as on desktop. Although sama data can't fit on smaller screen, previous non-responsive solution was more usable.

### PR DESCRIPTION
**Pull request by krzys-h**
This makes it scroll horizontally rather than removing columns on mobile

Closes #201

---
This change is [Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/314)

### CODE REVIEW

**Review by cytadela8 — CHANGES_REQUESTED** [review]
Remove `responsive: true` from datatables_config.js

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/314#-:-MRj4f5Z6xeHRN5m1SWF:bbd58lm)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by krzys-h — COMMENTED** [review]
> Remove responsive: true from datatables_config.js

Done

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/314#-:-MRli8Y16YuyZGn7I0bA:b-pl3wti)* status: 3 of 4 files reviewed, all discussions resolved

**Review by cytadela8 — APPROVED** [review]
:duck: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/314#-:-MRu_GCu5hM2CerzZFXd:bcmjph0)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by cytadela8 — APPROVED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/314)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
