### PR TITLE
Improve style

### PR DESCRIPTION
**Pull request by cytadela8**
Improvements related to recently merged #269. Now the status page looks ok on both desktop and mobile.
Zrzut ekranu z 2021-01-04 o 14 48 36
Zrzut ekranu z 2021-01-04 o 14 50 22
Zrzut ekranu z 2021-01-04 o 14 50 28

---
This change is [Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/279)

### CODE REVIEW

**Review by krzys-h — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 4 of 4 files at r3, 1 of 1 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/279)* status: all files reviewed, 8 unresolved discussions (waiting on @cytadela8)

___
*[templates/_workshopStatusTable.html, line 13 at r5](https://reviewable.io/reviews/warsztatywww/aplikacjawww/279#-MQCuDVG2njZ2r2w7qr2:-MQCuDVG2njZ2r2w7qr3:b-p69g4g) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/4182c37a9b0946acf82a8000816da54787ff3093/templates/_workshopStatusTable.html#L13)):*
> ```HTML
>     {% for workshop in your_workshops %}
>     <tr>
>       <th scope="row">
> ```

The hardcoded sizing of the columns was there for a reason, now the tables don't align between different editions


___
*[templates/base.html, line 134 at r5](https://reviewable.io/reviews/warsztatywww/aplikacjawww/279#-MQCtW1PB2DCIYfABY9R:-MQCtW1PB2DCIYfABY9S:btid2yn) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/4182c37a9b0946acf82a8000816da54787ff3093/templates/base.html#L134)):*
> ```HTML
>             <li><a href="{% url 'mydata_status' %}">Kwalifikacja</a></li>
> 
>             <li><a href="{% url 'workshops_add' current_year.pk %}">Zgłoś warsztaty!</a></li>
> ```

The navbar is too long now, it breaks the layout when you have all of the admin things on it


___
*[templates/base.html, line 137 at r5](https://reviewable.io/reviews/warsztatywww/aplikacjawww/279#-MQCtgfREqkaYBM5nbzv:-MQCtgfREqkaYBM5nbzw:bfa0xi9) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/4182c37a9b0946acf82a8000816da54787ff3093/templates/base.html#L137)):*
> ```HTML
> 
>             {% if user.is_authenticated %}
>               <li><a class="btn" href="{% url 'mydata_profile' %}">{{ user.first_name }} {{ user.last_name }}</a></li>
> ```

If you want to do this, remove the 'you are already logged in' view from login.html entirely and make it redirect to the profile instead. Also change `LOGIN_REDIRECT_URL` to the profile page. And while you're doing that, maybe change the login endpoints to `/accounts/login/` and `/accounts/logout/`? (those are the defaults, and we already use `/accounts` for login related stuff)
___
*[templates/mydata_status.html, line 9 at r5](https://reviewable.io/reviews/warsztatywww/aplikacjawww/279#-MQCwSCkBeWJxVbIDGD3:-MQCwSCkBeWJxVbIDGD4:b-vil6rb) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/4182c37a9b0946acf82a8000816da54787ff3093/templates/mydata_status.html#L9)):*
> ```HTML
>       {% include '_statusLabel.html' with status=current_status %}
>     </h2>
>     <h2 class="visible-xs"><span>Edycja {{ current_year }}<br/></span>
> ```

Change it to switch closer to a point where the longest labels no longer fit on one line - currently there are three possibilities, one line with big label, two lines with big label and two lines with small label, and the switch between 2 and 3 when resizing the browser window is weird.



___
*[templates/program.html, line 11 at r5](https://reviewable.io/reviews/warsztatywww/aplikacjawww/279#-MQCuz-k78JiaziqJjO9:-MQCuz-k78JiaziqJjOA:begynur) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/4182c37a9b0946acf82a8000816da54787ff3093/templates/program.html#L11)):*
> ```HTML
>       <h1>{{ title }}</h1>
>       {% if has_results %}
>         <p class="alert alert-info">Twoje rozwiązania zostały ocenione! Sprawdź wyniki w zakładce <a href="{% url 'mydata_status' %}">kwalifikacja</a>.</p>
> ```

The wording here seems to suggest that ALL of them have been graded - i'm not sure how to make it better though
___
*[wwwapp/views.py, line 92 at r5](https://reviewable.io/reviews/warsztatywww/aplikacjawww/279#-MQCxAC4CRb-RkGXTALN:-MQCxAC4CRb-RkGXTALO:bga1d69) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/4182c37a9b0946acf82a8000816da54787ff3093/wwwapp/views.py#L92)):*
> ```Python
>         context['has_results'] = any([
>             participation.qualification_result for participation
>             in WorkshopParticipant.objects.filter(participant=request.user.userprofile).all()
> ```

Change it to only count the current year.
___
*[wwwapp/views.py, line 92 at r5](https://reviewable.io/reviews/warsztatywww/aplikacjawww/279#-MQCybRm1rRFOoT7C_nN:-MQCybRm1rRFOoT7C_nO:b16hz55) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/4182c37a9b0946acf82a8000816da54787ff3093/wwwapp/views.py#L92)):*
> ```Python
>         context['has_results'] = any([
>             participation.qualification_result for participation
>             in WorkshopParticipant.objects.filter(participant=request.user.userprofile).all()
> ```

Minor, possibly rework the code so that it only pulls the WorkshopParticipant objects once (the database has to go through them anyway in the user_participation filter above).
___
*[wwwapp/views.py, line 92 at r5](https://reviewable.io/reviews/warsztatywww/aplikacjawww/279#-MQCyePy1RiPPjV8dZFC:-MQCyePz2rXrQRdDrocO:b-onom6v) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/4182c37a9b0946acf82a8000816da54787ff3093/wwwapp/views.py#L92)):*
> ```Python
>         context['has_results'] = any([
>             participation.qualification_result for participation
>             in WorkshopParticipant.objects.filter(participant=request.user.userprofile).all()
> ```

Add check for this in the workshop qualification tests? (speaking of which, the entire new status page thing should have some tests as well...)

**Review by krzys-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/279)* status: all files reviewed, 8 unresolved discussions (waiting on @cytadela8)

___
*[wwwapp/views.py, line 92 at r5](https://reviewable.io/reviews/warsztatywww/aplikacjawww/279#-MQCybRm1rRFOoT7C_nN:-MQD2vOW6mIOXfE6v8sK:bm3duuw) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/4182c37a9b0946acf82a8000816da54787ff3093/wwwapp/views.py#L92)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

Minor, possibly rework the code so that it only pulls the WorkshopParticipant objects once (the database has to go through them anyway in the user_participation filter above).
</blockquote></details>

Or maybe just query the database for existence instead since you don't need the data anyway
```python
WorkshopParticipant.filter(workshop__year=year, participant=request.user.userprofile, qualification_result__isnull=False).exists()
```
or
```python
WorkshopParticipant.filter(workshop__in=workshops, participant=request.user.userprofile, qualification_result__isnull=False).exists()
```
(not sure which query is more optimal for the database, but I think the second one?)

**Review by cytadela8 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/279)* status: all files reviewed, 8 unresolved discussions (waiting on @cytadela8 and @krzys-h)

___
*[templates/_workshopStatusTable.html, line 13 at r5](https://reviewable.io/reviews/warsztatywww/aplikacjawww/279#-MQCuDVG2njZ2r2w7qr2:-MQE--vo9XHS35FpYQpS:b2g3xqq) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/4182c37a9b0946acf82a8000816da54787ff3093/templates/_workshopStatusTable.html#L13)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

The hardcoded sizing of the columns was there for a reason, now the tables don't align between different editions


</blockquote></details>

Well, but hardcoded size looked bad on mobile. Automatic sizing works great for one table. We can try different hardcoded proportions... What do you propose?
___
*[templates/program.html, line 11 at r5](https://reviewable.io/reviews/warsztatywww/aplikacjawww/279#-MQCuz-k78JiaziqJjO9:-MQE-fSg2w0S-4hA6yNZ:b-tzndxt) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/4182c37a9b0946acf82a8000816da54787ff3093/templates/program.html#L11)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

The wording here seems to suggest that ALL of them have been graded - i'm not sure how to make it better though
</blockquote></details>

I put like 15 minutes of thought into it and this is the best thing I came up with. I really want to put something here for people that are used to see grading results on the program page.

**Review by krzys-h — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/279)* status: all files reviewed, 7 unresolved discussions (waiting on @cytadela8)

___
*[templates/_workshopStatusTable.html, line 13 at r5](https://reviewable.io/reviews/warsztatywww/aplikacjawww/279#-MQCuDVG2njZ2r2w7qr2:-MQEELJ18oc4Bqmid0-R:b-oyr4hh) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/4182c37a9b0946acf82a8000816da54787ff3093/templates/_workshopStatusTable.html#L13)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

Well, but hardcoded size looked bad on mobile. Automatic sizing works great for one table. We can try different hardcoded proportions... What do you propose?
</blockquote></details>

50/50 doesn't look bad... (but some of your spacing seems somewhat off)

**Review by cytadela8 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/279)* status: all files reviewed, 6 unresolved discussions (waiting on @cytadela8 and @krzys-h)

___
*[templates/_workshopStatusTable.html, line 13 at r5](https://reviewable.io/reviews/warsztatywww/aplikacjawww/279#-MQCuDVG2njZ2r2w7qr2:-MQEy19DBT7ll61-HROP:b-896fix) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/4182c37a9b0946acf82a8000816da54787ff3093/templates/_workshopStatusTable.html#L13)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

50/50 doesn't look bad... (but some of your spacing seems somewhat off)


</blockquote></details>

Done.
___
*[templates/base.html, line 137 at r5](https://reviewable.io/reviews/warsztatywww/aplikacjawww/279#-MQCtgfREqkaYBM5nbzv:-MQEzaOq5zaM0dyBs1gR:b-896fix) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/4182c37a9b0946acf82a8000816da54787ff3093/templates/base.html#L137)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

If you want to do this, remove the 'you are already logged in' view from login.html entirely and make it redirect to the profile instead. Also change `LOGIN_REDIRECT_URL` to the profile page. And while you're doing that, maybe change the login endpoints to `/accounts/login/` and `/accounts/logout/`? (those are the defaults, and we already use `/accounts` for login related stuff)
</blockquote></details>

Done.
___
*[templates/mydata_status.html, line 9 at r5](https://reviewable.io/reviews/warsztatywww/aplikacjawww/279#-MQCwSCkBeWJxVbIDGD3:-MQFJVya3Hk_QGOC77aH:b-qt3f3m) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/4182c37a9b0946acf82a8000816da54787ff3093/templates/mydata_status.html#L9)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

Change it to switch closer to a point where the longest labels no longer fit on one line - currently there are three possibilities, one line with big label, two lines with big label and two lines with small label, and the switch between 2 and 3 when resizing the browser window is weird.



</blockquote></details>

Changed so it gets small on md size displays
___
*[wwwapp/views.py, line 92 at r5](https://reviewable.io/reviews/warsztatywww/aplikacjawww/279#-MQCxAC4CRb-RkGXTALN:-MQF-_EiBdB3Eynt2Tn-:b-896fix) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/4182c37a9b0946acf82a8000816da54787ff3093/wwwapp/views.py#L92)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

Change it to only count the current year.
</blockquote></details>

Done.
___
*[wwwapp/views.py, line 92 at r5](https://reviewable.io/reviews/warsztatywww/aplikacjawww/279#-MQCyePy1RiPPjV8dZFC:-MQF9Mni0Fk33tFUCv20:b-896fix) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/4182c37a9b0946acf82a8000816da54787ff3093/wwwapp/views.py#L92)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

Add check for this in the workshop qualification tests? (speaking of which, the entire new status page thing should have some tests as well...)
</blockquote></details>

Done.

**Review by krzys-h — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r6, 1 of 1 files at r7, 2 of 2 files at r8, 5 of 5 files at r9, 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/279)* status: all files reviewed, 2 unresolved discussions (waiting on @cytadela8)

___
*[wwwapp/auth.py, line 35 at r9](https://reviewable.io/reviews/warsztatywww/aplikacjawww/279#-MQHYiTy1NvDBjZ4tJcy:-MQHYiTy1NvDBjZ4tJcz:b-3z5z55) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/39ec2b2f8e2795ee1b73ec977bd7fe9d8c12eab0/wwwapp/auth.py#L35)):*
> ```Python
>                 'User profile was missing for %s. This should have never happened.', request.user,
>                 extra={'request': request})
>         return redirect('mydata_status')
> ```

Use `settings.LOGIN_REDIRECT_URL` instead

**Review by cytadela8 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/279)* status: 12 of 16 files reviewed, 2 unresolved discussions (waiting on @krzys-h)

___
*[templates/base.html, line 134 at r5](https://reviewable.io/reviews/warsztatywww/aplikacjawww/279#-MQCtW1PB2DCIYfABY9R:-MQUF1g489h8X9R3uaE6:bnpstaa) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/4182c37a9b0946acf82a8000816da54787ff3093/templates/base.html#L134)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

The navbar is too long now, it breaks the layout when you have all of the admin things on it


</blockquote></details>

I fixed this by lowering distance between buttons on navbar. It may still happen on very-very long names (eg. two part-surnames), but it's kind of like before this PR. We should think what we can do for very long surnames.
___
*[wwwapp/auth.py, line 35 at r9](https://reviewable.io/reviews/warsztatywww/aplikacjawww/279#-MQHYiTy1NvDBjZ4tJcy:-MQUFLXO9WEHP1dm_ryG:b-896fix) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/39ec2b2f8e2795ee1b73ec977bd7fe9d8c12eab0/wwwapp/auth.py#L35)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

Use `settings.LOGIN_REDIRECT_URL` instead
</blockquote></details>

Done.

**Review by krzys-h — DISMISSED** [review]
> Reviewed 1 of 1 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, 2 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/279)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by krzys-h** [comment]
@cytadela8 Rebase... (did you change line ends in main.css or something? I didn't even notice it earlier)

**Review by cytadela8 — COMMENTED** [review]
There was indeed some mess in main.css. I removed change to LF (from CRLF) line endings. We can do that in a separate PR. Other files need checking...

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/279#-:-MQX19dzBXG-zNG9AFVH:b-kff8ou)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by krzys-h — COMMENTED** [review]
> Reviewed 16 of 16 files at r15.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/279)* status: 1 of 16 files reviewed, all discussions resolved (waiting on @krzys-h)

**Review by krzys-h — APPROVED** [review]
> Reviewed 1 of 1 files at r16, 4 of 4 files at r17, 1 of 1 files at r18, 2 of 2 files at r19, 5 of 5 files at r20, 1 of 1 files at r21, 1 of 1 files at r22, 2 of 2 files at r23.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/279)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by krzys-h** [comment]
I'm removing entire main.css in #286 anyway, so no need to worry about line ends (but it would be good to check other files indeed)

**Pull request merged**
