### PR TITLE
Replace pyup with dependabot

### PR DESCRIPTION
**Pull request by krzys-h**
pyup can't rebase its own pull requests and I already had to fix them manually twice. Let's just replace it with Dependabot, which is now built into GitHub and supports automatic rebasing of pull requests it opens and additionally handles npm.

---
This change is [Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/347)

### CODE REVIEW

**Comment by cytadela8** [comment]
Does it also show changelogs? I will merge when I have time to properly clean up pyup.

**Comment by krzys-h** [comment]
From what I've seen it does

**Review by cytadela8 — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/347)* status: all files reviewed, 1 unresolved discussion (waiting on @krzys-h)

___
*[.github/dependabot.yml, line 6 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/347#-MV6NjtC-rXF5JH6os_w:-MV6NjtC-rXF5JH6os_x:b67xss4) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/573e92a5f071304eca39e984b814da75ca37f607/.github/dependabot.yml#L6)):*
> ```YAML
>     directory: "/"
>     schedule:
>       interval: "daily"
> ```

Maybe we should set it to monthly or at leasy weakly?
```
interval: "weekly"
      day: "saturday"
```

**Review by krzys-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/347)* status: all files reviewed, 1 unresolved discussion (waiting on @cytadela8)

___
*[.github/dependabot.yml, line 6 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/347#-MV6NjtC-rXF5JH6os_w:-MV6OJBY7BKsNLD58EdY:b-z5srfa) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/573e92a5f071304eca39e984b814da75ca37f607/.github/dependabot.yml#L6)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

Maybe we should set it to monthly or at leasy weakly?
```
interval: "weekly"
      day: "saturday"
```
</blockquote></details>

I wanted to have quick feedback to see if it works how we want it to first. We can change it later if it does.

**Review by cytadela8 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/347)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
