### PR TITLE
Model naming cleanup

### PR DESCRIPTION
**Pull request by krzys-h**
I'm starting to get mad because of some bad naming conventions

* Rename WorkshopUserProfile -> CampParticipant (so that it matches the naming convention of WorkshopParticipant)
  * Rename related name UserProfile.workshop_profile -> UserProfile.camp_participation
  * Rename related name Camp.workshopuserprofile_set -> Camp.participants
  * Add unique_together
* Cleanup WorkshopParticipant
  * Rename WorkshopParticipant.participant to WorkshopParticipant.user_profile (to match CampParticipant, and because seeing workshop_participant.participant is confusing)
  * Rename related name Workshop.workshopparticipant_set -> Workshop.participants
    * Note: Workshop.participants now points to WorkshopParticipant object, rather than UserProfile, because it appears this is more often what we want
  * Rename related name UserProfile.workshopparticipant_set -> UserProfile.workshop_participation
* Cleanup Article
  * Rename related name Article.articlecontenthistory_set -> Article.content_history
    * And remove a method which implemented it manually...
  * Remove related name User.articlecontenthistory_set (from ArticleContentHistory.modified_by)
  * Remove related name User.article_set (from Article.modified_by)
* Rename related name User.userprofile to User.user_profile to match the convention used everywhere else

models

---
This change is [Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/571)

### CODE REVIEW

**Review by cytadela8 — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, 11 of 11 files at r2, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/571)* status: all files reviewed, 1 unresolved discussion (waiting on @krzys-h)

___
*[wwwapp/models.py, line 366 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/571#-MvwJaqW5VC12CNuqgfk:-MvwJaqW5VC12CNuqgfl:b9kklxd) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/4d26c6ba4051b7d4343d14cc6697f22cf091e5a0/wwwapp/models.py#L366)):*
> ```Python
>     qualification_problems = models.FileField(null=True, blank=True, upload_to="qualification", storage=UploadStorage())
>     solution_uploads_enabled = models.BooleanField(default=True)
>     participants = models.ManyToManyField(UserProfile, blank=True, related_name='workshops', through='WorkshopParticipant')
> ```

This was unused, right?

**Review by krzys-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/571)* status: all files reviewed, 1 unresolved discussion (waiting on @cytadela8)

___
*[wwwapp/models.py, line 366 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/571#-MvwJaqW5VC12CNuqgfk:-MykjOd08tC7B3jdkOEU:b-w8jhsm) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/4d26c6ba4051b7d4343d14cc6697f22cf091e5a0/wwwapp/models.py#L366)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

This was unused, right?
</blockquote></details>

Did you mean `solution_uploads_enabled` or `participants`? Reviewable shows your comment on the first one, but I think you meant the second because this is the line that was removed.

The `participants` field defined a relationship between `Workshop` and `UserProfile` through the `WorkshopParticipant` model. This was replaced with a more direct relationship between `Workshop` and `WorkshopParticipant` (defined using `related_name` on `WorkshopParticipant.workshops` [here](https://github.com/warsztatywww/aplikacjawww/pull/571/commits/6442ef1e6f602dda0f803ef8343aafa9fb0af106#diff-a54e462903859da67a7951c71d5caed378692571e801d9d84eed3f0213bfdbc8R458)), without throwing the `UserProfile` into this.

There were only two places in the code which used the old variant ([here](https://github.com/warsztatywww/aplikacjawww/pull/571/commits/6442ef1e6f602dda0f803ef8343aafa9fb0af106#diff-c1875f1990dad9a9770c9f01a9acfc1d2fc3f5951d5e676f752ec48c2777f083R57) and [here](https://github.com/warsztatywww/aplikacjawww/pull/571/commits/6442ef1e6f602dda0f803ef8343aafa9fb0af106#diff-6fba1c640097d81a84b254c1f552bf6b144045d23b4034d465dfe949b898e16fR289)), and a ton of places which couldn't use it because they needed to access to the `WorkshopParticipant` object instead of `UserProfile`, and that is impossible with `ManyToManyField`

**Review by cytadela8 — APPROVED** [review]
:duck: 

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/571#-:-Mypq68n-db_LvRUrAci:bcmjph0)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[wwwapp/models.py, line 366 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/571#-MvwJaqW5VC12CNuqgfk:-MyppoGrAEu3kfVizbYV:b-immszb) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/4d26c6ba4051b7d4343d14cc6697f22cf091e5a0/wwwapp/models.py#L366)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

Did you mean `solution_uploads_enabled` or `participants`? Reviewable shows your comment on the first one, but I think you meant the second because this is the line that was removed.

The `participants` field defined a relationship between `Workshop` and `UserProfile` through the `WorkshopParticipant` model. This was replaced with a more direct relationship between `Workshop` and `WorkshopParticipant` (defined using `related_name` on `WorkshopParticipant.workshops` [here](https://github.com/warsztatywww/aplikacjawww/pull/571/commits/6442ef1e6f602dda0f803ef8343aafa9fb0af106#diff-a54e462903859da67a7951c71d5caed378692571e801d9d84eed3f0213bfdbc8R458)), without throwing the `UserProfile` into this.

There were only two places in the code which used the old variant ([here](https://github.com/warsztatywww/aplikacjawww/pull/571/commits/6442ef1e6f602dda0f803ef8343aafa9fb0af106#diff-c1875f1990dad9a9770c9f01a9acfc1d2fc3f5951d5e676f752ec48c2777f083R57) and [here](https://github.com/warsztatywww/aplikacjawww/pull/571/commits/6442ef1e6f602dda0f803ef8343aafa9fb0af106#diff-6fba1c640097d81a84b254c1f552bf6b144045d23b4034d465dfe949b898e16fR289)), and a ton of places which couldn't use it because they needed to access to the `WorkshopParticipant` object instead of `UserProfile`, and that is impossible with `ManyToManyField`
</blockquote></details>

OK.

Btw, Actually when you click on "r1" in the top right of my comment you will see it was on r1 thus the removal of participants field.

**Review by krzys-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/571)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[wwwapp/models.py, line 366 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/571#-MvwJaqW5VC12CNuqgfk:-MypqOXoCWxLC36Lptmw:b-3xhak8) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/4d26c6ba4051b7d4343d14cc6697f22cf091e5a0/wwwapp/models.py#L366)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

OK.

Btw, Actually when you click on "r1" in the top right of my comment you will see it was on r1 thus the removal of participants field.
</blockquote></details>

Oh interesting, when you look at it in the full diff view the comment appears in a different place than in the r1 view...

**Pull request merged**
