### PR TITLE
Migration to bootstrap4 and NEW STYLE!

### PR DESCRIPTION
**Pull request by krzys-h**
screencapture-localhost-8000-me-status-2021-01-07-23_23_02

screencapture-localhost-8000-2021-workshop-dfsdfdf-edit-2021-01-07-22_15_02

Needs some more testing and small bugfixes (I removed almost all CSS along the way and recreated it from scratch...)

Depends on: ~~#283~~, ~~#282~~, ~~#279~~, ~~#272~~
Replaces/closes: #166 
Closes: #196

---
This change is [Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/286)

### CODE REVIEW

**Comment by krzys-h** [comment]
I'm opening this up for discussion because I think I've done most of the things I could do myself. Things to discuss before merging/fix after merging:
* ~~The links are too dark and hard to see~~
  Fixed, I changed the link color from `$primary` to `lighten($primary, 15%)` - I was afraid it would look bad because it's a different shade but it actually looks good
  image
* The default navbar font is too big and things don't fit
  We have a problem with the navbar again. We can decrease the font size, but tbh I never liked how tiny the font was on our original navbar. Currently, "Internety" is commented out and the qualification things were put back into a dropdown...
  As a plus, the bootstrap4 navbar layout at least breaks less with long names (but it still somewhat does)
  image
* The program page feels more empty than it did before
  The "W" logos are gone because the "well" component no longer exists in bootstrap and they were useless anyway
  image

**Review by cytadela8 — CHANGES_REQUESTED** [review]
Navbar needs further rework before this can be merged. There are some solutions that we should consider:
- smaller logo (version without text, main page already has big banner with text)
- reduce spacing between buttons (buttons look like you removed my spacing override?)
- consider changing profile button. (only first_name, crop two long surname, smaller font, remove name totally)

> Reviewed 43 of 43 files at r1.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/286#-:-MQmOZjD5v4PAIZBf2D5:b-cmunj)* status: all files reviewed, 3 unresolved discussions (waiting on @krzys-h)

___
*[frontend/index.ts, line 1 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/286#-MQmJkvD3x9aUUlSK5sk:-MQmJkvD3x9aUUlSK5sl:b-ifywt1) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/00502e8533d8a56d2b460599783016c49984d550/frontend/index.ts#L1)):*
> ```XML
> // jQuery and Bootstrap3 and Font Awesome
> ```

Bootstrap4
___
*[templates/base.html, line 63 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/286#-MQmNRba8JljAzHNKKJn:-MQmNRba8JljAzHNKKJo:b-x3ughb) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/00502e8533d8a56d2b460599783016c49984d550/templates/base.html#L63)):*
> ```HTML
>

**Review by krzys-h — COMMENTED** [review]
> buttons look like you removed my spacing override?

I removed all CSS and copied back only the parts which were absolutely necessary

---

We can also try to move the navbar out of `<div class="container">` which will cause it to stretch across entire top of the page

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/286#-:-MQmSy-l9Jq06VxNd7NI:b-6n4qox)* status: all files reviewed, 3 unresolved discussions (waiting on @cytadela8 and @krzys-h)

___
*[templates/base.html, line 63 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/286#-MQmNRba8JljAzHNKKJn:-MQmTjNYCOl3Q61NdeNQ:bikvoz0) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/00502e8533d8a56d2b460599783016c49984d550/templates/base.html#L63)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

I don't like removing "Internety" This is the only place where you can access those resources and I want to possibly expand access to resources from past workshops, not cripple it...
</blockquote></details>

Yeah I know, this is temporary until we figure out what to do with the navbar
___
*[templates/base.html, line 129 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/286#-MQmNHzy1gYykv5mQwIv:-MQmTwgH0QDjXSy3ysKm:berxxx7) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/00502e8533d8a56d2b460599783016c49984d550/templates/base.html#L129)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

I really don't like putting those two things into one dropdown. We have to find a better solution for our navbar
</blockquote></details>

This is just temporary until we figure out the navbar too

**Review by krzys-h — COMMENTED** [review]
> I think the website should also look ok if somebody decides to use eg. half of their laptop screen.

Half of a 1080p laptop screen is already using the collapsed navbar, even on current `master`, so no, it does not leave the issue on smaller screens. This solution does look a bit weird through because our logo is almost as wide as the left margin but not precisely, making it look a bit misaligned, and I couldn't find a way to align just the links to the container.

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/286#-:-MQsQyCw0nt748EHNJMT:bmkxlmp)* status: all files reviewed, 3 unresolved discussions (waiting on @cytadela8 and @krzys-h)

**Review by cytadela8 — COMMENTED** [review]
What about QHD displays (2560x1440)? :stuck_out_tongue_closed_eyes: There are also other scenarios like me having a wide tab bar on the left side of the window. OR my tablet that does show full navbar, but there is little space on the left and right side of it. (see screenshot on Discord). I think we should try to make sure public facing parts of website work well on many different resolutions.

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/286#-:-MQsUeMFB6S0xPJmTcDo:baiok7x)* status: all files reviewed, 3 unresolved discussions (waiting on @cytadela8 and @krzys-h)

**Review by cytadela8 — CHANGES_REQUESTED** [review]
I found some styling issues

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/286#-:-MReeKRFB4HR7Zg4bkde:bbz5m7y)* status: all files reviewed, 5 unresolved discussions (waiting on @cytadela8 and @krzys-h)

___
*[templates/_programworkshop.html, line 22 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/286#-MRec72oACn9Kzup1r17:-MRec72oACn9Kzup1r18:b-xuk1is) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/00502e8533d8a56d2b460599783016c49984d550/templates/_programworkshop.html#L22)):*
> ```HTML
>   {% else %}
>     {% if registered %}
>       <div>
> ```

This is too tall in new bootstrap due to bigger font. See SS:
NEW

OLD

___
*[templates/mydata_base.html, line 6 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/286#-MRedN9N7riZML53cu7r:-MRedN9N7riZML53cu7s:bnssek8) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/00502e8533d8a56d2b460599783016c49984d550/templates/mydata_base.html#L6)):*
> ```HTML
>   <h1>{{ title }}</h1>
>   <nav class="mb-3">
>     <ul class="nav float-md-right my-3 my-md-0 mx-3 justify-content-center">
> ```

Profile navbar no longer looks so good on small resolution. My main issue is with the logout button although I liked previous behaviour in general.
**OLD**


**NEW**

**Review by krzys-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/286)* status: 35 of 43 files reviewed, 4 unresolved discussions (waiting on @cytadela8)

___
*[templates/_programworkshop.html, line 22 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/286#-MRec72oACn9Kzup1r17:-MRf3TO0CFR4113sG87X:b-g4lj0y) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/00502e8533d8a56d2b460599783016c49984d550/templates/_programworkshop.html#L22)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

This is too tall in new bootstrap due to bigger font. See SS:
NEW

OLD


</blockquote></details>

Do you mean just the header or the entire thing?
___
*[templates/base.html, line 63 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/286#-MQmNRba8JljAzHNKKJn:-MRf27UKCAEpptZgBS3B:bk7pbv5) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/00502e8533d8a56d2b460599783016c49984d550/templates/base.html#L63)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

Yeah I know, this is temporary until we figure out what to do with the navbar
</blockquote></details>

Done by @cytadela8 
___
*[templates/base.html, line 129 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/286#-MQmNHzy1gYykv5mQwIv:-MRf29rlCCfXIPAeKE5v:bk7pbv5) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/00502e8533d8a56d2b460599783016c49984d550/templates/base.html#L129)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

I suggest not merging this temporarily :P
I will try to find a temporary CSS solution to restore all the buttons. I agree we should find a more permanent solution to improve our navbar. I would like to insist for usability over design. New design is pretty, but less usable due to worse buttons.
</blockquote></details>

Done by @cytadela8 
___
*[templates/base.html, line 57 at r4](https://reviewable.io/reviews/warsztatywww/aplikacjawww/286#-MRf2JiJ26iMnHsg2zXd:-MRf2JiJ26iMnHsg2zXe:b-5u43zj) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/f436510a6b6f5845d8b400b4c6adeda1e99c9b9d/templates/base.html#L57)):*
> ```HTML
>             <li class="nav-item">
>               <a class="nav-link" href="{% url 'index' %}">
>                 <span class="fas fa-home d-none d-lg-block"></span>
> ```

The icon is not correctly aligned to the text for some reason. Also it would probably be better do do `<span class="d-none d-lg-block"><i class="fas fa-home"></i></span>` instead. Also from a quick test in dev tools that fixes the issue, so I fixed it myself ¯\\_(ツ)_/¯


___
*[templates/mydata_base.html, line 6 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/286#-MRedN9N7riZML53cu7r:-MRf2C3PCr2v6i4uOqFV:b-o3rhd) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/00502e8533d8a56d2b460599783016c49984d550/templates/mydata_base.html#L6)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

Profile navbar no longer looks so good on small resolution. My main issue is with the logout button although I liked previous behaviour in general.
**OLD**


**NEW**





</blockquote></details>

I agree, will fix this later

**Review by cytadela8 — CHANGES_REQUESTED** [review]
Just the two issues introduced by new bootstrap. I think we can merge after those are fixed

> Reviewed 5 of 6 files at r2, 3 of 3 files at r5, 1 of 1 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/286#-:-MRftUsi1Nbk6wPhU7W7:bzhdrii)* status: all files reviewed, 2 unresolved discussions (waiting on @cytadela8 and @krzys-h)

___
*[templates/_programworkshop.html, line 22 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/286#-MRec72oACn9Kzup1r17:-MRfqu9T7e-sdvuqcOty:b-fa7jif) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/00502e8533d8a56d2b460599783016c49984d550/templates/_programworkshop.html#L22)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

Do you mean just the header or the entire thing?
</blockquote></details>

Look at the difference between size of workshop "Umieć" and "Tablica" due to big font of "Byłeś zapisany" "Tablica." is signifficantly taller.

**Review by krzys-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/286)* status: 35 of 43 files reviewed, 2 unresolved discussions (waiting on @cytadela8)

___
*[templates/_programworkshop.html, line 22 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/286#-MRec72oACn9Kzup1r17:-MRgOHpI51lEuK4ARQsn:bt6vl08) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/00502e8533d8a56d2b460599783016c49984d550/templates/_programworkshop.html#L22)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

Look at the difference between size of workshop "Umieć" and "Tablica" due to big font of "Byłeś zapisany" "Tablica." is signifficantly taller.
</blockquote></details>

Ah, I see what you meant now. Fixed.
___
*[templates/mydata_base.html, line 6 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/286#-MRedN9N7riZML53cu7r:-MRgOMLO7hlFYYv4jJUm:b-896fix) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/00502e8533d8a56d2b460599783016c49984d550/templates/mydata_base.html#L6)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

I agree, will fix this later
</blockquote></details>

Done.

**Review by cytadela8 — APPROVED** [review]
> Reviewed 6 of 6 files at r8, 1 of 1 files at r9, 2 of 2 files at r10, 2 of 2 files at r11, 3 of 3 files at r12, 2 of 2 files at r13, 1 of 1 files at r14.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/286)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by cytadela8 — DISMISSED** [review]
:duck: :duck: :duck: :duck: :duck: :duck: :duck: :duck: :duck: :duck: :duck: :duck: :duck: :duck: :duck: :duck: :duck: :duck: :duck: :duck: :duck: :duck: :duck: :duck: 

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/286#-:-MRj3ffB5j8O64jvVjxm:b-hv1wfv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by cytadela8 — APPROVED** [review]
:duck: 

> Reviewed 1 of 1 files at r15, 5 of 5 files at r16, 1 of 1 files at r17.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/286#-:-MRjQTpG2069KLdapxYU:bcmjph0)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
