### PR TITLE
Better fake data generator

### PR DESCRIPTION
**Pull request by cytadela8**
This change is [Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/616)

### CODE REVIEW

**Review by krzys-h — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/616)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by krzys-h** [comment]
Fix your unit tests

**Review by cytadela8 — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/616#-:-N9yePJRA74fLqy-X4By:bb6un1j)* status: 1 of 2 files reviewed, all discussions resolved

**Review by krzys-h — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/616)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
