### PR TITLE
Display info about currently uploaded qualification problems in the workshop editor

### PR DESCRIPTION
**Pull request by krzys-h**
This change is [Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/396)

### CODE REVIEW

**Review by cytadela8 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/396)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @krzys-h)

___
*[wwwapp/forms.py, line 241 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/396#-MVBWrVU93y-pW5yc08R:-MVBWrVU93y-pW5yc08S:bbzibbt) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/f9423446ae623e4951300b977e6851d38a8291d4/wwwapp/forms.py#L241)):*
> ```Python
>         # Display link to current qualification tasks:
>         if self.instance.qualification_problems:
>             self.fields['qualification_problems'].help_text = format_html('Aktualnie: <a href="{}">{}</a>', reverse('qualification_problems', args=[self.instance.year.pk, self.instance.name]), os.path.basename(self.instance.qualification_problems.path))
> ```

please add `target="_blank"`

**Review by cytadela8 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/396)* status: all files reviewed, 1 unresolved discussion (waiting on @krzys-h)

**Review by krzys-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/396)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @cytadela8)

___
*[wwwapp/forms.py, line 241 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/396#-MVBWrVU93y-pW5yc08R:-MVBXxHK5UH2jfzBq1I3:b-896fix) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/f9423446ae623e4951300b977e6851d38a8291d4/wwwapp/forms.py#L241)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

please add `target="_blank"`
</blockquote></details>

Done.

**Review by cytadela8 — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/396)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by cytadela8 — APPROVED** [review]
:duck: 

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/396#-:-MVBclzE-KP8A8EGRyPw:bcmjph0)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
