### PR TITLE
Soft-delete solution files

### LINKED ISSUE #356: Add version history to solutions
We wanted to have version history for solutions. Since the attachments can't be edited (only deleted and reuploaded), the most logical way to implement this would probably be to make the file deletion soft-delete instead - this will allow admins to recover previous versions of the files if ever needed.

Do we need to expose this functionality to lecturers? I personally don't think so - they have the last modification date and that should be enough for them.

### PR DESCRIPTION
**Pull request by krzys-h**
This makes it possible to recover deleted files / browse upload history.

For now, the deleted files are only accessible through Django admin.

Closes #356

---
This change is [Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/363)

### CODE REVIEW

**Review by cytadela8 — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/363)* status: all files reviewed, 1 unresolved discussion (waiting on @krzys-h)

___
*[wwwapp/admin.py, line 166 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/363#-MV66t600J0t5R5BKQhQ:-MV66t600J0t5R5BKQhR:b-umc5o2) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/6025a5ad487fa153ece0845067763dd85b71c670/wwwapp/admin.py#L166)):*
> ```Python
>     def get_queryset(self, request):
>         queryset = self.model.all_objects
>         # The below is copied from the base implementation in BaseModelAdmin to prevent other changes in behavior
> ```

Probably could have used super, but whatever

**Review by cytadela8 — APPROVED** [review]
I understand for now we can only hard-delete from console?

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/363#-:-MV69QNxEmszfG2fBU3a:bhhxf9u)* status: all files reviewed, 1 unresolved discussion (waiting on @krzys-h)

**Review by krzys-h — COMMENTED** [review]
> I understand for now we can only hard-delete from console?

Yes. I don't expect we'll ever actually need it unless somebody uploads a ton of huge files or something.

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/363#-:-MV6A7MOEHc7DnMQsanl:bmh2tg6)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[wwwapp/admin.py, line 166 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/363#-MV66t600J0t5R5BKQhQ:-MV69Xky1DRn_JhIg0r1:bwbyat3) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/6025a5ad487fa153ece0845067763dd85b71c670/wwwapp/admin.py#L166)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

Probably could have used super, but whatever
</blockquote></details>

Actually, you couldn't - the super method hardcodes `self.model._default_manager.get_queryset()`, and the default manager doesn't list the deleted objects which I want to be visible in the admin panel. This is also based on the first Google result for "soft-delete in Django" :P

**Review by cytadela8 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/363)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
