### PR TITLE
Remove OPENSHIFT leftovers

### PR DESCRIPTION
**Pull request by cytadela8**
- We don't use OPENSHIFT for a long time. Instead config is in a special
  python file local_settings
- Adjust relevant checking for API keys
- Also update admin list

This will bring our repo config to state usable on production.

---
This change is [Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/253)

### CODE REVIEW

**Review by krzys-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/253)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @enedil, @gorbak25, @krzys-h, and @Matyt)

___
*[wwwapp/settings_prod.py, line 32 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/253#-MPeoybNCBEw6fpgG35z:-MPeoybNCBEw6fpgG36-:b6gau1k) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/618c0118dc34a1f456549cd4f6f72a57b899e498/wwwapp/settings_prod.py#L32)):*
> ```Python
> CSRF_COOKIE_SECURE = True
> 
> MEDIA_ROOT = None  # set in local_settings
> ```

`./media` would probably be a more reasonable default
___
*[wwwapp/settings_prod.py, line 34 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/253#-MPepNxT7hhQfQjDKvJF:-MPepNxT7hhQfQjDKvJG:b-3nfrpi) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/618c0118dc34a1f456549cd4f6f72a57b899e498/wwwapp/settings_prod.py#L34)):*
> ```Python
> MEDIA_ROOT = None  # set in local_settings
> 
> from .local_settings import *
> ```

Maybe verify that all required options were set similarly to how the OAuth ones are handled? And make sure it doesn't crash if this file doesn't exist (report the unset variables instead). I'm not sure if I even care that much though.

**Review by krzys-h — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/253)* status: all files reviewed, 3 unresolved discussions (waiting on @cytadela8, @enedil, @gorbak25, and @Matyt)

___
*[wwwapp/__init__.py, line 59 at r2](https://reviewable.io/reviews/warsztatywww/aplikacjawww/253#-MPfEJ0H83xYgIl1RHVv:-MPfEJ0H83xYgIl1RHVw:b-7wfm6e) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/c8729de0d693cfaa8ad51979e240d1c7dca8eaf3/wwwapp/__init__.py#L59)):*
> ```Python
>     path = settings.MEDIA_ROOT + 'check.txt'
>     with open(path, 'w') as f:
>         f.write("Check")
> ```

Being unable to write the file in the configured location should be a warning as well - I accidentally set MEDIA_ROOT to / while testing and it crashed with PermissionError
___
*[wwwapp/__init__.py, line 59 at r2](https://reviewable.io/reviews/warsztatywww/aplikacjawww/253#-MPfEUUV8RRMOI1fVxka:-MPfEUUV8RRMOI1fVxkb:bgcn9za) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/c8729de0d693cfaa8ad51979e240d1c7dca8eaf3/wwwapp/__init__.py#L59)):*
> ```Python
>     path = settings.MEDIA_ROOT + 'check.txt'
>     with open(path, 'w') as f:
>         f.write("Check")
> ```

Remove the temporary file after the check
___
*[wwwapp/__init__.py, line 64 at r2](https://reviewable.io/reviews/warsztatywww/aplikacjawww/253#-MPfEolUB6_HRrnY60by:-MPfEolUB6_HRrnY60bz:b-tab9so) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/c8729de0d693cfaa8ad51979e240d1c7dca8eaf3/wwwapp/__init__.py#L64)):*
> ```Python
>     for host in settings.ALLOWED_HOSTS:
>         try:
>             url = "https://" + host+settings.MEDIA_URL+'check.txt'
> ```

I'm not sure how the server is configured, but is there a chance that Django can start up before nginx and fail this check?

**Review by cytadela8 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/253)* status: all files reviewed, 3 unresolved discussions (waiting on @cytadela8, @enedil, @gorbak25, @krzys-h, and @Matyt)

___
*[wwwapp/__init__.py, line 64 at r2](https://reviewable.io/reviews/warsztatywww/aplikacjawww/253#-MPfEolUB6_HRrnY60by:-MPnT_4u2F14RmLB539o:bpwde2o) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/c8729de0d693cfaa8ad51979e240d1c7dca8eaf3/wwwapp/__init__.py#L64)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

I'm not sure how the server is configured, but is there a chance that Django can start up before nginx and fail this check?
</blockquote></details>

Even if it does I don't think this is a problem. We will just see a warning in logs. This is really a warning in it's full sense. This is meant to inform me if there might be some problems. I would run probably `./manege.py check` after a prod update and this may flag a nginx config problem.
___
*[wwwapp/settings_prod.py, line 32 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/253#-MPeoybNCBEw6fpgG35z:-MPnTO493RkXOOteiGDw:byulfm7) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/618c0118dc34a1f456549cd4f6f72a57b899e498/wwwapp/settings_prod.py#L32)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

`./media` would probably be a more reasonable default
</blockquote></details>

Instead of setting a default added checks.
___
*[wwwapp/settings_prod.py, line 34 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/253#-MPepNxT7hhQfQjDKvJF:-MPnTN-PEKaMpBu8ofA3:bb6un1j) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/618c0118dc34a1f456549cd4f6f72a57b899e498/wwwapp/settings_prod.py#L34)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

Maybe verify that all required options were set similarly to how the OAuth ones are handled? And make sure it doesn't crash if this file doesn't exist (report the unset variables instead). I'm not sure if I even care that much though.
</blockquote></details>

Done

**Review by cytadela8 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/253)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @enedil, @gorbak25, @krzys-h, and @Matyt)

___
*[wwwapp/__init__.py, line 59 at r2](https://reviewable.io/reviews/warsztatywww/aplikacjawww/253#-MPfEUUV8RRMOI1fVxka:-MPnYNf97ItHknMJx4qM:b-896fix) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/c8729de0d693cfaa8ad51979e240d1c7dca8eaf3/wwwapp/__init__.py#L59)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

Remove the temporary file after the check
</blockquote></details>

Done.
___
*[wwwapp/__init__.py, line 59 at r2](https://reviewable.io/reviews/warsztatywww/aplikacjawww/253#-MPfEJ0H83xYgIl1RHVv:-MPnYNumAOd4BwgR81i3:b-896fix) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/c8729de0d693cfaa8ad51979e240d1c7dca8eaf3/wwwapp/__init__.py#L59)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

Being unable to write the file in the configured location should be a warning as well - I accidentally set MEDIA_ROOT to / while testing and it crashed with PermissionError
</blockquote></details>

Done.

**Review by krzys-h — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/253)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enedil, @gorbak25, and @Matyt)

**Review by krzys-h — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/253)* status: all files reviewed, 1 unresolved discussion (waiting on @cytadela8, @enedil, @gorbak25, and @Matyt)

___
*[wwwapp/__init__.py, line 66 at r3](https://reviewable.io/reviews/warsztatywww/aplikacjawww/253#-MPnjqbwEI62IfXXTn-i:-MPnjqbx04n4hcysVaEt:b13tgy9) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/04d5b8f4581c4d9b2d5a1f5129be12f6ee0d1657/wwwapp/__init__.py#L66)):*
> ```Python
>         for host in settings.ALLOWED_HOSTS:
>             try:
>                 url = "https://" + host + settings.MEDIA_URL + 'check.txt'
> ```

Fix tests - this fails with `*` in debug config

**Review by cytadela8 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/253)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @enedil, @gorbak25, @krzys-h, and @Matyt)

___
*[wwwapp/__init__.py, line 66 at r3](https://reviewable.io/reviews/warsztatywww/aplikacjawww/253#-MPnjqbwEI62IfXXTn-i:-MPnmn1W50DOPRrhVRw0:b-896fix) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/04d5b8f4581c4d9b2d5a1f5129be12f6ee0d1657/wwwapp/__init__.py#L66)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

Fix tests - this fails with `*` in debug config
</blockquote></details>

Done.

**Review by krzys-h — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/253)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enedil, @gorbak25, and @Matyt)

**Pull request merged**
