### PR TITLE
Introduce the Camp model

### LINKED ISSUE #151: Introduce Camp/Workshops model
After so many editions(and two extra editions dubbed WWWX) it would be useful to introduce a Camp model so we can use this app for generic qualifications for any type of Camp/Workshop. This would remove the need of hard coding some settings and additionally would simplify some things.

### PR DESCRIPTION
**Pull request by krzys-h**
This is a work-in-progress attempt to introduce the Camp model and stop using ints for camp editions everywhere, and removes hardcoded things like current year from settings. Most things seem to work, but it definitely needs more testing (lack of unit testing really hurts here :<)

After the migration is done, CURRENT_YEAR, WORKSHOPS_START_DATE and WORKSHOPS_END_DATE can be removed from settings.py.

Closes #151

TODO:
* remove-owncloud was merged into this temporarily because I don't want to be fixing code that we are removing in a moment anyway, but the branch obviously needs to be rebased after that PR is merged
* run the typechecker
* test all the things

In the future:
* think about how to adapt this for things WWWx - right now there are still some things that depend on the year value, just wrapped into another object
* perhaps do more with it: add fields like where it took place, who was the organizer at the time etc. and autogenerate the history page from this?
* maybe auto-update deadlines in articles using data from this model so that we can stop doing it manually?

---
This change is [Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/230)

### CODE REVIEW

**Comment by krzys-h** [comment]
Also closes #32

**Review by cytadela8 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/230)* status: 5 of 17 files reviewed, 1 unresolved discussion (waiting on @cytadela8, @gorbak25, and @krzys-h)

___
*[templates/workshopproposal.html, line 67 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/230#-MFCkJ8eAz5ravrT3X3r:-MFCkJ8eAz5ravrT3X3s:b-32f0hu) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/addbe76282f7eaefad96214f5782ab0bdd164741/templates/workshopproposal.html#L67)):*
> ```HTML
>       {% else %}
>         {% if new %}
>           Zgłoszenia warsztatów nie są obecnie aktywne
> ```

This is under `if new`? What is new?

**Review by krzys-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/230)* status: 5 of 17 files reviewed, 1 unresolved discussion (waiting on @cytadela8 and @gorbak25)

___
*[templates/workshopproposal.html, line 67 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/230#-MFCkJ8eAz5ravrT3X3r:-MFCmUFK9v-ZrvgHWQD-:bu48pdn) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/addbe76282f7eaefad96214f5782ab0bdd164741/templates/workshopproposal.html#L67)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

This is under `if new`? What is new?
</blockquote></details>

New means that you are trying to create a new workshop proposal, rather than edit the existing one - it may be better to make this `if not workshop`...

has_edit_perms (this changed block) can be false for one of the following reasons:
1. You are trying to submit a new proposal, but we are not accepting proposals right now - this is a new addition, since I added `are_proposals_open` in the Camp model
2. You are not allowed to edit an existing proposal (but you have view permissions)

**Review by cytadela8 — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r4, 2 of 2 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/230#-:-MFV3i4n1U_njjYhXkBp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gorbak25)

**Pull request merged**
